const std = @import("std");

pub const Language = enum {
    english,
    chinese,
};

pub const TextId = enum {
    camera,
    idle,
    move,
    rotate,
    scale,
    mode,
    toggle_camera,
    focus,
    empty,
    cube,
    sphere,
    light,
    asset,
    instantiate_slash_load,
    select_a_model_or_scene_in_content_browser_to_instantiate_slash_load_it,
    viewport_target_is_not_ready_yet,
    backend,
    device,
    drawable,
    viewport,
    entities,
    meshes,
    lights,
    cameras,
    file,
    save_scene,
    load_scene,
    create,
    plane,
    point_light,
    edit,
    duplicate,
    delete,
    parent_to_active,
    unparent,
    window,
    reset_dock_layout,
    scene_filter,
    scene_root,
    no_entity_selected,
    selection_is_stale,
    selection_count,
    identity,
    entity_id,
    editor_only,
    components,
    add_cube_mesh,
    add_sphere_mesh,
    add_plane_mesh,
    set_cube_mesh,
    set_sphere_mesh,
    set_plane_mesh,
    remove_mesh_component,
    add_camera_component,
    remove_camera_component,
    add_directional_light,
    add_point_light,
    add_spot_light,
    remove_light_component,
    mesh,
    primitive,
    resource,
    vertices,
    indices,
    triangles,
    mesh_component_has_no_bound_resource,
    material,
    shared_by,
    scope,
    instance,
    texture,
    none,
    embedded,
    make_material_instance,
    editing_now_will_affect_all_users_until_instanced,
    assign_selected_texture,
    clear_texture,
    shading,
    base_color,
    opacity,
    name,
    parent,
    unparent_selected,
    root,
    local_translation,
    local_rotation,
    local_scale,
    world_translation,
    world_rotation,
    world_scale,
    primary_scene_camera,
    make_primary_camera,
    use_perspective,
    use_orthographic,
    near_clip,
    far_clip,
    size,
    directional,
    point,
    spot,
    color,
    intensity,
    range,
    refresh,
    quick_save,
    selected,
    type,
    path,
    save_over_selected_scene,
    load_selected_scene,
    instantiate_selected_model,
    no_asset_selected,
    asset_filter,
    scenes,
    models,
    textures,
    shaders,
    use_this_texture_from_details_gt_material,
    models_are_imported_as_grouped_instances_with_a_movable_root_entity,
    instantiate_model,
    scenes_can_be_loaded_directly_or_overwritten_from_the_current_world,
    save_over,
    shader_source_preview_is_currently_metadata_only,
    previewing,
    select_a_texture_asset_or_an_entity_with_a_textured_material_to_preview_it,
    language,
    viewport_size,
    the_dock_layout_uses_stable_panel_ids_now_so_language_switching_no_longer_breaks_docking,
    scene,
    model,
    shader,
    custom,
    unlit,
    lambert,
    viewport_toolbar,
    stats,
    details,
    content_browser,
    asset_preview,
    settings,
    editor,
    english,
    chinese,
};

pub fn text(language: Language, id: TextId) []const u8 {
    return switch (language) {
        .english => switch (id) {
            .camera => "Camera",
            .idle => "Idle",
            .move => "Move",
            .rotate => "Rotate",
            .scale => "Scale",
            .mode => "Mode",
            .toggle_camera => "Toggle Camera",
            .focus => "Focus",
            .empty => "Empty",
            .cube => "Cube",
            .sphere => "Sphere",
            .light => "Light",
            .asset => "Asset",
            .instantiate_slash_load => "Instantiate / Load",
            .select_a_model_or_scene_in_content_browser_to_instantiate_slash_load_it => "Select a model or scene in Content Browser to instantiate/load it.",
            .viewport_target_is_not_ready_yet => "Viewport target is not ready yet.",
            .backend => "Backend",
            .device => "Device",
            .drawable => "Drawable",
            .viewport => "Viewport",
            .entities => "Entities",
            .meshes => "Meshes",
            .lights => "Lights",
            .cameras => "Cameras",
            .file => "File",
            .save_scene => "Save Scene",
            .load_scene => "Load Scene",
            .create => "Create",
            .plane => "Plane",
            .point_light => "Point Light",
            .edit => "Edit",
            .duplicate => "Duplicate",
            .delete => "Delete",
            .parent_to_active => "Parent To Active",
            .unparent => "Unparent",
            .window => "Window",
            .reset_dock_layout => "Reset Dock Layout",
            .scene_filter => "Scene Filter",
            .scene_root => "Scene Root",
            .no_entity_selected => "No entity selected.",
            .selection_is_stale => "Selection is stale.",
            .selection_count => "Selection Count",
            .identity => "Identity",
            .entity_id => "Entity ID",
            .editor_only => "Editor Only",
            .components => "Components",
            .add_cube_mesh => "Add Cube Mesh",
            .add_sphere_mesh => "Add Sphere Mesh",
            .add_plane_mesh => "Add Plane Mesh",
            .set_cube_mesh => "Set Cube Mesh",
            .set_sphere_mesh => "Set Sphere Mesh",
            .set_plane_mesh => "Set Plane Mesh",
            .remove_mesh_component => "Remove Mesh Component",
            .add_camera_component => "Add Camera Component",
            .remove_camera_component => "Remove Camera Component",
            .add_directional_light => "Add Directional Light",
            .add_point_light => "Add Point Light",
            .add_spot_light => "Add Spot Light",
            .remove_light_component => "Remove Light Component",
            .mesh => "Mesh",
            .primitive => "Primitive",
            .resource => "Resource",
            .vertices => "Vertices",
            .indices => "Indices",
            .triangles => "Triangles",
            .mesh_component_has_no_bound_resource => "Mesh component has no bound resource.",
            .material => "Material",
            .shared_by => "Shared By",
            .scope => "Scope",
            .instance => "Instance",
            .texture => "Texture",
            .none => "None",
            .embedded => "Embedded",
            .make_material_instance => "Make Material Instance",
            .editing_now_will_affect_all_users_until_instanced => "Editing now will affect all users until instanced.",
            .assign_selected_texture => "Assign Selected Texture",
            .clear_texture => "Clear Texture",
            .shading => "Shading",
            .base_color => "Base Color",
            .opacity => "Opacity",
            .name => "Name",
            .parent => "Parent",
            .unparent_selected => "Unparent Selected",
            .root => "Root",
            .local_translation => "Local Translation",
            .local_rotation => "Local Rotation",
            .local_scale => "Local Scale",
            .world_translation => "World Translation",
            .world_rotation => "World Rotation",
            .world_scale => "World Scale",
            .primary_scene_camera => "Primary scene camera",
            .make_primary_camera => "Make Primary Camera",
            .use_perspective => "Use Perspective",
            .use_orthographic => "Use Orthographic",
            .near_clip => "Near Clip",
            .far_clip => "Far Clip",
            .size => "Size",
            .directional => "Directional",
            .point => "Point",
            .spot => "Spot",
            .color => "Color",
            .intensity => "Intensity",
            .range => "Range",
            .refresh => "Refresh",
            .quick_save => "Quick Save",
            .selected => "Selected",
            .type => "Type",
            .path => "Path",
            .save_over_selected_scene => "Save Over Selected Scene",
            .load_selected_scene => "Load Selected Scene",
            .instantiate_selected_model => "Instantiate Selected Model",
            .no_asset_selected => "No asset selected.",
            .asset_filter => "Asset Filter",
            .scenes => "Scenes",
            .models => "Models",
            .textures => "Textures",
            .shaders => "Shaders",
            .use_this_texture_from_details_gt_material => "Use this texture from Details > Material.",
            .models_are_imported_as_grouped_instances_with_a_movable_root_entity => "Models are imported as grouped instances with a movable root entity.",
            .instantiate_model => "Instantiate Model",
            .scenes_can_be_loaded_directly_or_overwritten_from_the_current_world => "Scenes can be loaded directly or overwritten from the current world.",
            .save_over => "Save Over",
            .shader_source_preview_is_currently_metadata_only => "Shader source preview is currently metadata-only.",
            .previewing => "Previewing",
            .select_a_texture_asset_or_an_entity_with_a_textured_material_to_preview_it => "Select a texture asset or an entity with a textured material to preview it.",
            .language => "Language",
            .viewport_size => "Viewport Size",
            .the_dock_layout_uses_stable_panel_ids_now_so_language_switching_no_longer_breaks_docking => "The dock layout uses stable panel ids now, so language switching no longer breaks docking.",
            .scene => "Scene",
            .model => "Model",
            .shader => "Shader",
            .custom => "Custom",
            .unlit => "Unlit",
            .lambert => "Lambert",
            .viewport_toolbar => "Viewport Toolbar",
            .stats => "Stats",
            .details => "Details",
            .content_browser => "Content Browser",
            .asset_preview => "Asset Preview",
            .settings => "Settings",
            .editor => "Editor",
            .english => "English",
            .chinese => "Chinese",
        },
        .chinese => switch (id) {
            .camera => "相机",
            .idle => "空闲",
            .move => "移动",
            .rotate => "旋转",
            .scale => "缩放",
            .mode => "模式",
            .toggle_camera => "切换相机",
            .focus => "聚焦",
            .empty => "空物体",
            .cube => "立方体",
            .sphere => "球体",
            .light => "灯光",
            .asset => "资源",
            .instantiate_slash_load => "实例化 / 加载",
            .select_a_model_or_scene_in_content_browser_to_instantiate_slash_load_it => "在资源浏览器里选择模型或场景后可直接实例化或加载。",
            .viewport_target_is_not_ready_yet => "视口渲染目标尚未准备完成。",
            .backend => "后端",
            .device => "设备",
            .drawable => "绘制尺寸",
            .viewport => "视口",
            .entities => "对象",
            .meshes => "网格",
            .lights => "灯光",
            .cameras => "相机",
            .file => "文件",
            .save_scene => "保存场景",
            .load_scene => "加载场景",
            .create => "创建",
            .plane => "平面",
            .point_light => "点光源",
            .edit => "编辑",
            .duplicate => "复制",
            .delete => "删除",
            .parent_to_active => "设为活动对象子级",
            .unparent => "取消父级",
            .window => "窗口",
            .reset_dock_layout => "重置停靠布局",
            .scene_filter => "场景过滤",
            .scene_root => "场景根节点",
            .no_entity_selected => "未选择对象。",
            .selection_is_stale => "选择已失效。",
            .selection_count => "选择数量",
            .identity => "标识",
            .entity_id => "对象 ID",
            .editor_only => "仅编辑器",
            .components => "组件",
            .add_cube_mesh => "添加立方体网格",
            .add_sphere_mesh => "添加球体网格",
            .add_plane_mesh => "添加平面网格",
            .set_cube_mesh => "设为立方体网格",
            .set_sphere_mesh => "设为球体网格",
            .set_plane_mesh => "设为平面网格",
            .remove_mesh_component => "移除网格组件",
            .add_camera_component => "添加相机组件",
            .remove_camera_component => "移除相机组件",
            .add_directional_light => "添加平行光",
            .add_point_light => "添加点光",
            .add_spot_light => "添加聚光",
            .remove_light_component => "移除灯光组件",
            .mesh => "网格",
            .primitive => "图元",
            .resource => "资源",
            .vertices => "顶点",
            .indices => "索引",
            .triangles => "三角形",
            .mesh_component_has_no_bound_resource => "网格组件还没有绑定资源。",
            .material => "材质",
            .shared_by => "共享数量",
            .scope => "范围",
            .instance => "实例",
            .texture => "贴图",
            .none => "无",
            .embedded => "嵌入",
            .make_material_instance => "创建材质实例",
            .editing_now_will_affect_all_users_until_instanced => "当前资源仍在共享，不实例化就会影响所有引用。",
            .assign_selected_texture => "指定所选贴图",
            .clear_texture => "清除贴图",
            .shading => "着色",
            .base_color => "基础颜色",
            .opacity => "不透明度",
            .name => "名称",
            .parent => "父级",
            .unparent_selected => "取消父级",
            .root => "根节点",
            .local_translation => "局部位移",
            .local_rotation => "局部旋转",
            .local_scale => "局部缩放",
            .world_translation => "世界位移",
            .world_rotation => "世界旋转",
            .world_scale => "世界缩放",
            .primary_scene_camera => "当前主场景相机",
            .make_primary_camera => "设为主相机",
            .use_perspective => "透视投影",
            .use_orthographic => "正交投影",
            .near_clip => "近裁剪面",
            .far_clip => "远裁剪面",
            .size => "尺寸",
            .directional => "平行光",
            .point => "点光",
            .spot => "聚光",
            .color => "颜色",
            .intensity => "强度",
            .range => "范围",
            .refresh => "刷新",
            .quick_save => "快速保存",
            .selected => "已选",
            .type => "类型",
            .path => "路径",
            .save_over_selected_scene => "覆盖保存到所选场景",
            .load_selected_scene => "加载所选场景",
            .instantiate_selected_model => "实例化所选模型",
            .no_asset_selected => "未选择资源。",
            .asset_filter => "资源过滤",
            .scenes => "场景",
            .models => "模型",
            .textures => "贴图",
            .shaders => "着色器",
            .use_this_texture_from_details_gt_material => "可在 细节 > 材质 中把这张贴图指定给当前对象。",
            .models_are_imported_as_grouped_instances_with_a_movable_root_entity => "模型会作为成组实例导入，并自动生成可整体移动的根节点。",
            .instantiate_model => "实例化模型",
            .scenes_can_be_loaded_directly_or_overwritten_from_the_current_world => "场景资源可以直接加载，也可以用当前世界覆盖保存。",
            .save_over => "覆盖保存",
            .shader_source_preview_is_currently_metadata_only => "当前着色器预览仅提供元数据展示。",
            .previewing => "预览中",
            .select_a_texture_asset_or_an_entity_with_a_textured_material_to_preview_it => "选择贴图资源，或选择一个带贴图材质的对象来预览。",
            .language => "语言",
            .viewport_size => "视口尺寸",
            .the_dock_layout_uses_stable_panel_ids_now_so_language_switching_no_longer_breaks_docking => "停靠布局现在使用稳定的面板 ID，切换语言也不会打乱停靠位置。",
            .scene => "场景",
            .model => "模型",
            .shader => "着色器",
            .custom => "自定义",
            .unlit => "无光照",
            .lambert => "兰伯特",
            .viewport_toolbar => "视口工具条",
            .stats => "状态",
            .details => "细节",
            .content_browser => "资源浏览",
            .asset_preview => "资产预览",
            .settings => "设置",
            .editor => "编辑器",
            .english => "英文",
            .chinese => "中文",
        },
    };
}

pub fn panelLabel(language: Language, buffer: []u8, id: TextId, stable_id: []const u8) ![]const u8 {
    return std.fmt.bufPrint(buffer, "{s}###{s}", .{ text(language, id), stable_id });
}

pub fn legacyText(language: Language, english_value: []const u8, chinese_fallback: []const u8) []const u8 {
    const id = textIdForEnglish(english_value) orelse return switch (language) {
        .english => english_value,
        .chinese => chinese_fallback,
    };
    return text(language, id);
}

fn textIdForEnglish(english_value: []const u8) ?TextId {
    inline for ([_]struct { key: []const u8, id: TextId }{
        .{ .key = "Camera", .id = .camera },
        .{ .key = "Idle", .id = .idle },
        .{ .key = "Move", .id = .move },
        .{ .key = "Rotate", .id = .rotate },
        .{ .key = "Scale", .id = .scale },
        .{ .key = "Mode", .id = .mode },
        .{ .key = "Toggle Camera", .id = .toggle_camera },
        .{ .key = "Focus", .id = .focus },
        .{ .key = "Empty", .id = .empty },
        .{ .key = "Cube", .id = .cube },
        .{ .key = "Sphere", .id = .sphere },
        .{ .key = "Light", .id = .light },
        .{ .key = "Asset", .id = .asset },
        .{ .key = "Instantiate / Load", .id = .instantiate_slash_load },
        .{ .key = "Select a model or scene in Content Browser to instantiate/load it.", .id = .select_a_model_or_scene_in_content_browser_to_instantiate_slash_load_it },
        .{ .key = "Viewport target is not ready yet.", .id = .viewport_target_is_not_ready_yet },
        .{ .key = "Backend", .id = .backend },
        .{ .key = "Device", .id = .device },
        .{ .key = "Drawable", .id = .drawable },
        .{ .key = "Viewport", .id = .viewport },
        .{ .key = "Entities", .id = .entities },
        .{ .key = "Meshes", .id = .meshes },
        .{ .key = "Lights", .id = .lights },
        .{ .key = "Cameras", .id = .cameras },
        .{ .key = "File", .id = .file },
        .{ .key = "Save Scene", .id = .save_scene },
        .{ .key = "Load Scene", .id = .load_scene },
        .{ .key = "Create", .id = .create },
        .{ .key = "Plane", .id = .plane },
        .{ .key = "Point Light", .id = .point_light },
        .{ .key = "Edit", .id = .edit },
        .{ .key = "Duplicate", .id = .duplicate },
        .{ .key = "Delete", .id = .delete },
        .{ .key = "Parent To Active", .id = .parent_to_active },
        .{ .key = "Unparent", .id = .unparent },
        .{ .key = "Window", .id = .window },
        .{ .key = "Reset Dock Layout", .id = .reset_dock_layout },
        .{ .key = "Scene Filter", .id = .scene_filter },
        .{ .key = "Scene Root", .id = .scene_root },
        .{ .key = "No entity selected.", .id = .no_entity_selected },
        .{ .key = "Selection is stale.", .id = .selection_is_stale },
        .{ .key = "Selection Count", .id = .selection_count },
        .{ .key = "Identity", .id = .identity },
        .{ .key = "Entity ID", .id = .entity_id },
        .{ .key = "Editor Only", .id = .editor_only },
        .{ .key = "Components", .id = .components },
        .{ .key = "Add Cube Mesh", .id = .add_cube_mesh },
        .{ .key = "Add Sphere Mesh", .id = .add_sphere_mesh },
        .{ .key = "Add Plane Mesh", .id = .add_plane_mesh },
        .{ .key = "Set Cube Mesh", .id = .set_cube_mesh },
        .{ .key = "Set Sphere Mesh", .id = .set_sphere_mesh },
        .{ .key = "Set Plane Mesh", .id = .set_plane_mesh },
        .{ .key = "Remove Mesh Component", .id = .remove_mesh_component },
        .{ .key = "Add Camera Component", .id = .add_camera_component },
        .{ .key = "Remove Camera Component", .id = .remove_camera_component },
        .{ .key = "Add Directional Light", .id = .add_directional_light },
        .{ .key = "Add Point Light", .id = .add_point_light },
        .{ .key = "Add Spot Light", .id = .add_spot_light },
        .{ .key = "Remove Light Component", .id = .remove_light_component },
        .{ .key = "Mesh", .id = .mesh },
        .{ .key = "Primitive", .id = .primitive },
        .{ .key = "Resource", .id = .resource },
        .{ .key = "Vertices", .id = .vertices },
        .{ .key = "Indices", .id = .indices },
        .{ .key = "Triangles", .id = .triangles },
        .{ .key = "Mesh component has no bound resource.", .id = .mesh_component_has_no_bound_resource },
        .{ .key = "Material", .id = .material },
        .{ .key = "Shared By", .id = .shared_by },
        .{ .key = "Scope", .id = .scope },
        .{ .key = "Instance", .id = .instance },
        .{ .key = "Texture", .id = .texture },
        .{ .key = "None", .id = .none },
        .{ .key = "Embedded", .id = .embedded },
        .{ .key = "Make Material Instance", .id = .make_material_instance },
        .{ .key = "Editing now will affect all users until instanced.", .id = .editing_now_will_affect_all_users_until_instanced },
        .{ .key = "Assign Selected Texture", .id = .assign_selected_texture },
        .{ .key = "Clear Texture", .id = .clear_texture },
        .{ .key = "Shading", .id = .shading },
        .{ .key = "Base Color", .id = .base_color },
        .{ .key = "Opacity", .id = .opacity },
        .{ .key = "Name", .id = .name },
        .{ .key = "Parent", .id = .parent },
        .{ .key = "Unparent Selected", .id = .unparent_selected },
        .{ .key = "Root", .id = .root },
        .{ .key = "Local Translation", .id = .local_translation },
        .{ .key = "Local Rotation", .id = .local_rotation },
        .{ .key = "Local Scale", .id = .local_scale },
        .{ .key = "World Translation", .id = .world_translation },
        .{ .key = "World Rotation", .id = .world_rotation },
        .{ .key = "World Scale", .id = .world_scale },
        .{ .key = "Primary scene camera", .id = .primary_scene_camera },
        .{ .key = "Make Primary Camera", .id = .make_primary_camera },
        .{ .key = "Use Perspective", .id = .use_perspective },
        .{ .key = "Use Orthographic", .id = .use_orthographic },
        .{ .key = "Near Clip", .id = .near_clip },
        .{ .key = "Far Clip", .id = .far_clip },
        .{ .key = "Size", .id = .size },
        .{ .key = "Directional", .id = .directional },
        .{ .key = "Point", .id = .point },
        .{ .key = "Spot", .id = .spot },
        .{ .key = "Color", .id = .color },
        .{ .key = "Intensity", .id = .intensity },
        .{ .key = "Range", .id = .range },
        .{ .key = "Refresh", .id = .refresh },
        .{ .key = "Quick Save", .id = .quick_save },
        .{ .key = "Selected", .id = .selected },
        .{ .key = "Type", .id = .type },
        .{ .key = "Path", .id = .path },
        .{ .key = "Save Over Selected Scene", .id = .save_over_selected_scene },
        .{ .key = "Load Selected Scene", .id = .load_selected_scene },
        .{ .key = "Instantiate Selected Model", .id = .instantiate_selected_model },
        .{ .key = "No asset selected.", .id = .no_asset_selected },
        .{ .key = "Asset Filter", .id = .asset_filter },
        .{ .key = "Scenes", .id = .scenes },
        .{ .key = "Models", .id = .models },
        .{ .key = "Textures", .id = .textures },
        .{ .key = "Shaders", .id = .shaders },
        .{ .key = "Use this texture from Details > Material.", .id = .use_this_texture_from_details_gt_material },
        .{ .key = "Models are imported as grouped instances with a movable root entity.", .id = .models_are_imported_as_grouped_instances_with_a_movable_root_entity },
        .{ .key = "Instantiate Model", .id = .instantiate_model },
        .{ .key = "Scenes can be loaded directly or overwritten from the current world.", .id = .scenes_can_be_loaded_directly_or_overwritten_from_the_current_world },
        .{ .key = "Save Over", .id = .save_over },
        .{ .key = "Shader source preview is currently metadata-only.", .id = .shader_source_preview_is_currently_metadata_only },
        .{ .key = "Previewing", .id = .previewing },
        .{ .key = "Select a texture asset or an entity with a textured material to preview it.", .id = .select_a_texture_asset_or_an_entity_with_a_textured_material_to_preview_it },
        .{ .key = "Language", .id = .language },
        .{ .key = "Viewport Size", .id = .viewport_size },
        .{ .key = "The dock layout uses stable panel ids now, so language switching no longer breaks docking.", .id = .the_dock_layout_uses_stable_panel_ids_now_so_language_switching_no_longer_breaks_docking },
        .{ .key = "Scene", .id = .scene },
        .{ .key = "Model", .id = .model },
        .{ .key = "Shader", .id = .shader },
        .{ .key = "Custom", .id = .custom },
        .{ .key = "Unlit", .id = .unlit },
        .{ .key = "Lambert", .id = .lambert },
        .{ .key = "Viewport Toolbar", .id = .viewport_toolbar },
        .{ .key = "Stats", .id = .stats },
        .{ .key = "Details", .id = .details },
        .{ .key = "Content Browser", .id = .content_browser },
        .{ .key = "Asset Preview", .id = .asset_preview },
        .{ .key = "Settings", .id = .settings },
        .{ .key = "Editor", .id = .editor },
        .{ .key = "English", .id = .english },
        .{ .key = "Chinese", .id = .chinese },
    }) |entry| {
        if (std.mem.eql(u8, english_value, entry.key)) return entry.id;
    }
    return null;
}
