#ifndef GUAVA_NEXT_SDL3_SHIM_H
#define GUAVA_NEXT_SDL3_SHIM_H

#include <SDL3/SDL.h>

#if defined(__APPLE__)
#include <SDL3/SDL_metal.h>
#endif

enum {
	GUAVA_SDL_WINDOW_RESIZABLE = SDL_WINDOW_RESIZABLE,
	GUAVA_SDL_WINDOW_HIGH_PIXEL_DENSITY = SDL_WINDOW_HIGH_PIXEL_DENSITY,
	GUAVA_SDL_WINDOW_METAL = SDL_WINDOW_METAL,
	GUAVA_SDL_EVENT_QUIT = SDL_EVENT_QUIT,
	GUAVA_SDL_EVENT_WINDOW_RESIZED = SDL_EVENT_WINDOW_RESIZED,
	GUAVA_SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED = SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED,
	GUAVA_SDL_EVENT_WINDOW_METAL_VIEW_RESIZED = SDL_EVENT_WINDOW_METAL_VIEW_RESIZED,
	GUAVA_SDL_EVENT_WINDOW_CLOSE_REQUESTED = SDL_EVENT_WINDOW_CLOSE_REQUESTED,
	GUAVA_SDL_EVENT_WINDOW_DESTROYED = SDL_EVENT_WINDOW_DESTROYED,
};

#endif