import Foundation
import AssetPipeline
import GuavaUIRuntime
import IntentRuntime
import RenderBackend
import SceneRuntime
import ScriptRuntime
import SIMDCompat

extension EditorSceneAdapter {
    func particleEmitterSection(for entity: EntityID) -> EditorInspectorSection? {
        guard scene.component(ParticleEmitter.self, for: entity) != nil else { return nil }
        return EditorInspectorSection(
            id: "particle-emitter",
            title: L("Particle Emitter"),
            fields: [
                EditorInspectorField(id: "particle-module-stack", label: L("Modules"),
                                     value: .particleModuleStack(particleModuleStackBinding(for: entity))),
                EditorInspectorField(id: "particle-emitting", label: L("Emitting"),
                                     value: .bool(particleBoolBinding(for: entity, \.settings.emission.isEmitting,
                                                                      summary: "Toggle particle emitting"))),
                EditorInspectorField(id: "particle-looping", label: L("Looping"),
                                     value: .bool(particleBoolBinding(for: entity, \.settings.emission.looping,
                                                                      summary: "Toggle particle looping"))),
                EditorInspectorField(id: "particle-simulation-space", label: L("Space"),
                                     value: .particleSimulationSpace(particleSimulationSpaceBinding(for: entity))),
                EditorInspectorField(id: "particle-simulation-backend", label: L("Backend"),
                                     value: .particleSimulationBackend(particleSimulationBackendBinding(for: entity))),
                EditorInspectorField(id: "particle-gpu-workgroup-size", label: L("GPU Workgroup"),
                                     value: .constrainedNumber(particleIntBinding(for: entity,
                                                                                  \.settings.gpuSimulation.workgroupSize,
                                                                                  summary: "Update GPU particle workgroup size"),
                                                               min: 1,
                                                               max: Float(ParticleGPUSimulationPlan.maximumWorkgroupSize),
                                                               step: 1,
                                                               showsStepper: true)),
                EditorInspectorField(id: "particle-gpu-status", label: L("GPU Status"),
                                     value: .readOnly(particleGPUStatusLabel(for: entity))),
                EditorInspectorField(id: "particle-duration", label: L("Duration"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.emission.duration,
                                                                                    summary: "Update particle duration"),
                                                               min: 0, max: 600, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-simulation-speed", label: L("Speed"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.emission.simulationSpeed,
                                                                                    summary: "Update particle simulation speed"),
                                                               min: 0, max: 16, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-prewarm-time", label: L("Prewarm"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.emission.prewarmTime,
                                                                                    summary: "Update particle prewarm"),
                                                               min: 0, max: 600, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-prewarm-step", label: L("Prewarm Step"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.emission.prewarmStep,
                                                                                    summary: "Update particle prewarm step"),
                                                               min: 0.004, max: 1, step: 0.01, showsStepper: true)),
                EditorInspectorField(id: "particle-rate", label: L("Emission Rate"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.emission.emissionRate,
                                                                                    summary: "Update emission rate"),
                                                               min: 0, max: 1000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-rate-curve", label: L("Rate Curve"),
                                     value: .particleCurve(particleCurveBinding(for: entity, \.settings.emission.emissionRateCurve,
                                                                                summary: "Update particle rate curve"))),
                EditorInspectorField(id: "particle-distance-rate", label: L("Rate over Distance"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.emission.distanceEmissionRate,
                                                                                    summary: "Update distance emission rate"),
                                                               min: 0, max: 1000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-distance-rate-curve", label: L("Distance Curve"),
                                     value: .particleCurve(particleCurveBinding(for: entity, \.settings.emission.distanceEmissionRateCurve,
                                                                                summary: "Update particle distance rate curve"))),
                EditorInspectorField(id: "particle-burst-count", label: L("Burst Count"),
                                     value: .constrainedNumber(particleIntBinding(for: entity, \.settings.emission.burstCount,
                                                                                  summary: "Update particle burst count"),
                                                               min: 0, max: 100_000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-burst-interval", label: L("Burst Interval"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.emission.burstInterval,
                                                                                    summary: "Update particle burst interval"),
                                                               min: 0, max: 60, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-max", label: L("Max Particles"),
                                     value: .constrainedNumber(particleMaxBinding(for: entity),
                                                               min: 0, max: 100_000, step: 16, showsStepper: true)),
                EditorInspectorField(id: "particle-max-spawned-per-frame", label: L("Max Spawn / Frame"),
                                     value: .constrainedNumber(particleIntBinding(for: entity,
                                                                                  \.settings.emission.maxSpawnedParticlesPerFrame,
                                                                                  summary: "Update particle spawn budget"),
                                                               min: 0, max: 100_000, step: 16, showsStepper: true)),
                EditorInspectorField(id: "particle-max-rendered", label: L("Max Rendered"),
                                     value: .constrainedNumber(particleIntBinding(for: entity, \.settings.emission.maxRenderedParticles,
                                                                                  summary: "Update max rendered particles"),
                                                               min: 0, max: 100_000, step: 16, showsStepper: true)),
                EditorInspectorField(id: "particle-lifetime", label: L("Lifetime"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.appearance.lifetime,
                                                                                    summary: "Update particle lifetime"),
                                                               min: 0, max: 60, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-sub-emitter-trigger", label: L("Sub Emit"),
                                     value: .particleSubEmitterTrigger(particleSubEmitterTriggerBinding(for: entity))),
                EditorInspectorField(id: "particle-sub-emitter-burst", label: L("Sub Count"),
                                     value: .constrainedNumber(particleIntBinding(for: entity, \.settings.subEmitters.legacyBurstCount,
                                                                                  summary: "Update sub-emitter count"),
                                                               min: 0, max: 10_000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-sub-emitter-probability", label: L("Sub Chance"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity,
                                                                                    \.settings.subEmitters.legacyProbability,
                                                                                    summary: "Update sub-emitter chance"),
                                                               min: 0, max: 1, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-sub-emitter-depth", label: L("Sub Depth"),
                                     value: .constrainedNumber(particleIntBinding(for: entity, \.settings.subEmitters.legacyMaxDepth,
                                                                                  summary: "Update sub-emitter depth"),
                                                               min: 0, max: 16, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-sub-emitter-inherit", label: L("Sub Inherit"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity,
                                                                                    \.settings.subEmitters.legacyInheritVelocity,
                                                                                    summary: "Update sub-emitter inheritance"),
                                                               min: 0, max: 10, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-sub-emitter-lifetime", label: L("Sub Lifetime"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.subEmitters.legacyLifetime,
                                                                                    summary: "Update sub-emitter lifetime"),
                                                               min: 0.0001, max: 60, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-sub-emitter-velocity", label: L("Sub Velocity"),
                                     value: .vector3(x: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.subEmitters.legacyStartVelocity,
                                                                               axis: 0,
                                                                               summary: "Update sub-emitter velocity"),
                                                     y: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.subEmitters.legacyStartVelocity,
                                                                               axis: 1,
                                                                               summary: "Update sub-emitter velocity"),
                                                     z: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.subEmitters.legacyStartVelocity,
                                                                               axis: 2,
                                                                               summary: "Update sub-emitter velocity"))),
                EditorInspectorField(id: "particle-sub-emitter-velocity-random", label: L("Sub Vel Random"),
                                     value: .vector3(x: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.subEmitters.legacyVelocityRandomness,
                                                                               axis: 0,
                                                                               summary: "Update sub-emitter velocity randomness"),
                                                     y: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.subEmitters.legacyVelocityRandomness,
                                                                               axis: 1,
                                                                               summary: "Update sub-emitter velocity randomness"),
                                                     z: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.subEmitters.legacyVelocityRandomness,
                                                                               axis: 2,
                                                                               summary: "Update sub-emitter velocity randomness"))),
                EditorInspectorField(id: "particle-sub-emitter-start-size", label: L("Sub Start Size"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity,
                                                                                    \.settings.subEmitters.legacyStartSize,
                                                                                    summary: "Update sub-emitter start size"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-sub-emitter-end-size", label: L("Sub End Size"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity,
                                                                                    \.settings.subEmitters.legacyEndSize,
                                                                                    summary: "Update sub-emitter end size"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-sub-emitter-start-color", label: L("Sub Start Color"),
                                     value: .color(particleSubEmitterColorBinding(for: entity, isStart: true))),
                EditorInspectorField(id: "particle-sub-emitter-end-color", label: L("Sub End Color"),
                                     value: .color(particleSubEmitterColorBinding(for: entity, isStart: false))),
                EditorInspectorField(id: "particle-sub-emitters", label: L("Sub Emitters"),
                                     value: .particleSubEmitters(particleSubEmittersBinding(for: entity))),
                EditorInspectorField(id: "particle-shape", label: L("Shape"),
                                     value: .particleEmissionShape(particleShapeBinding(for: entity))),
                EditorInspectorField(id: "particle-spawn-radius", label: L("Spawn Radius"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.shape.spawnRadius,
                                                                                    summary: "Update spawn radius"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-box-extents", label: L("Box Extents"),
                                     value: .vector3(x: particleBoxExtentsBinding(for: entity, axis: 0),
                                                     y: particleBoxExtentsBinding(for: entity, axis: 1),
                                                     z: particleBoxExtentsBinding(for: entity, axis: 2))),
                EditorInspectorField(id: "particle-cone-radius", label: L("Cone Radius"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.shape.coneRadius,
                                                                                    summary: "Update cone radius"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-cone-height", label: L("Cone Height"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.shape.coneHeight,
                                                                                    summary: "Update cone height"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-start-size", label: L("Start Size"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.appearance.startSize,
                                                                                    summary: "Update start size"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-end-size", label: L("End Size"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.appearance.endSize,
                                                                                    summary: "Update end size"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-size-randomness", label: L("Size Random"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.appearance.sizeRandomness,
                                                                                    summary: "Update size randomness"),
                                                               min: 0, max: 4, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-rotation", label: L("Rotation"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.appearance.startRotation,
                                                                                    summary: "Update particle rotation"),
                                                               min: -1000, max: 1000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-rotation-randomness", label: L("Rot Random"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.appearance.rotationRandomness,
                                                                                    summary: "Update rotation randomness"),
                                                               min: 0, max: 1000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-angular-velocity", label: L("Spin"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.appearance.angularVelocity,
                                                                                    summary: "Update particle spin"),
                                                               min: -1000, max: 1000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-angular-velocity-randomness", label: L("Spin Random"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.appearance.angularVelocityRandomness,
                                                                                    summary: "Update spin randomness"),
                                                               min: 0, max: 1000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-velocity-inheritance", label: L("Velocity Inherit"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.velocity.velocityInheritance,
                                                                                    summary: "Update velocity inheritance"),
                                                               min: 0, max: 10, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-size-curve", label: L("Size Curve"),
                                     value: .particleCurve(particleCurveBinding(for: entity, \.settings.appearance.sizeCurve,
                                                                                summary: "Update particle size curve"))),
                EditorInspectorField(id: "particle-gravity", label: L("Gravity"),
                                     value: .vector3(x: particleGravityBinding(for: entity, axis: 0),
                                                     y: particleGravityBinding(for: entity, axis: 1),
                                                     z: particleGravityBinding(for: entity, axis: 2))),
                EditorInspectorField(id: "particle-noise-strength", label: L("Noise Strength"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.noiseStrength,
                                                                                    summary: "Update particle noise strength"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-noise-scale", label: L("Noise Scale"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.noiseScale,
                                                                                    summary: "Update particle noise scale"),
                                                               min: 0.0001, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-noise-speed", label: L("Noise Speed"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.noiseSpeed,
                                                                                    summary: "Update particle noise speed"),
                                                               min: 0, max: 100, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-force-mode", label: L("Force"),
                                     value: .particleForceMode(particleForceModeBinding(for: entity))),
                EditorInspectorField(id: "particle-force-center", label: L("Force Center"),
                                     value: .vector3(x: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.forceCenter,
                                                                               axis: 0,
                                                                               summary: "Update particle force center"),
                                                     y: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.forceCenter,
                                                                               axis: 1,
                                                                               summary: "Update particle force center"),
                                                     z: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.forceCenter,
                                                                               axis: 2,
                                                                               summary: "Update particle force center"))),
                EditorInspectorField(id: "particle-force-axis", label: L("Force Axis"),
                                     value: .vector3(x: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.forceAxis,
                                                                               axis: 0,
                                                                               summary: "Update particle force axis"),
                                                     y: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.forceAxis,
                                                                               axis: 1,
                                                                               summary: "Update particle force axis"),
                                                     z: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.forceAxis,
                                                                               axis: 2,
                                                                               summary: "Update particle force axis"))),
                EditorInspectorField(id: "particle-force-radius", label: L("Force Radius"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.forceRadius,
                                                                                    summary: "Update particle force radius"),
                                                               min: 0, max: 10_000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-force-strength", label: L("Force Strength"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.forceStrength,
                                                                                    summary: "Update particle force strength"),
                                                               min: -10_000, max: 10_000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-force-falloff", label: L("Force Falloff"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.forceFalloff,
                                                                                    summary: "Update particle force falloff"),
                                                               min: 0, max: 16, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-vector-field-mode", label: L("Vector Field"),
                                     value: .particleVectorFieldMode(particleVectorFieldModeBinding(for: entity))),
                EditorInspectorField(id: "particle-vector-field-direction", label: L("Field Direction"),
                                     value: .vector3(x: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.vectorFieldDirection,
                                                                               axis: 0,
                                                                               summary: "Update vector field direction"),
                                                     y: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.vectorFieldDirection,
                                                                               axis: 1,
                                                                               summary: "Update vector field direction"),
                                                     z: particleVectorBinding(for: entity,
                                                                               keyPath: \.settings.forces.vectorFieldDirection,
                                                                               axis: 2,
                                                                               summary: "Update vector field direction"))),
                EditorInspectorField(id: "particle-vector-field-strength", label: L("Field Strength"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.vectorFieldStrength,
                                                                                    summary: "Update vector field strength"),
                                                               min: -10_000, max: 10_000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-vector-field-scale", label: L("Field Scale"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.vectorFieldScale,
                                                                                    summary: "Update vector field scale"),
                                                               min: 0.0001, max: 1_000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-vector-field-scroll", label: L("Field Scroll"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.forces.vectorFieldScrollSpeed,
                                                                                    summary: "Update vector field scroll"),
                                                               min: 0, max: 1_000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-collision-mode", label: L("Collision"),
                                     value: .particleCollisionMode(particleCollisionModeBinding(for: entity))),
                EditorInspectorField(id: "particle-collision-plane-y", label: L("Plane Y"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.collision.collisionPlaneY,
                                                                                    summary: "Update particle collision plane"),
                                                               min: -10_000, max: 10_000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-collision-restitution", label: L("Restitution"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.collision.collisionRestitution,
                                                                                    summary: "Update particle restitution"),
                                                               min: 0, max: 1, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-collision-damping", label: L("Damping"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.collision.collisionDamping,
                                                                                    summary: "Update particle damping"),
                                                               min: 0, max: 1, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-start-color", label: L("Start Color"),
                                     value: .color(particleColorBinding(for: entity, isStart: true))),
                EditorInspectorField(id: "particle-end-color", label: L("End Color"),
                                     value: .color(particleColorBinding(for: entity, isStart: false))),
                EditorInspectorField(id: "particle-color-curve", label: L("Color Curve"),
                                     value: .particleCurve(particleCurveBinding(for: entity, \.settings.appearance.colorCurve,
                                                                                summary: "Update particle color curve"))),
                EditorInspectorField(id: "particle-blend-mode", label: L("Blend"),
                                     value: .particleBlendMode(particleBlendModeBinding(for: entity))),
                EditorInspectorField(id: "particle-render-mode", label: L("Render Mode"),
                                     value: .particleRenderMode(particleRenderModeBinding(for: entity))),
                EditorInspectorField(id: "particle-sort-mode", label: L("Sort"),
                                     value: .particleSortMode(particleSortModeBinding(for: entity))),
                EditorInspectorField(id: "particle-ribbon-width-scale", label: L("Ribbon Width"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.ribbonWidthScale,
                                                                                    summary: "Update ribbon width"),
                                                               min: 0, max: 100, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-ribbon-tail-width", label: L("Ribbon Tail Width"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.ribbonTailWidthScale,
                                                                                    summary: "Update ribbon tail width"),
                                                               min: 0, max: 10, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-ribbon-tail-alpha", label: L("Ribbon Tail Alpha"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.ribbonTailAlphaScale,
                                                                                    summary: "Update ribbon tail alpha"),
                                                               min: 0, max: 1, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-ribbon-max-segment", label: L("Ribbon Max Segment"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.ribbonMaxSegmentLength,
                                                                                    summary: "Update ribbon max segment"),
                                                               min: 0, max: 100_000, step: 0.1, showsStepper: true)),
                EditorInspectorField(id: "particle-ribbon-join-overlap", label: L("Ribbon Join Overlap"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.ribbonJoinOverlapScale,
                                                                                    summary: "Update ribbon join overlap"),
                                                               min: 0, max: 10, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-ribbon-smoothing", label: L("Ribbon Smoothing"),
                                     value: .constrainedNumber(particleClampedIntBinding(for: entity,
                                                                                         \.settings.trails.ribbonSmoothingSegments,
                                                                                         min: 1,
                                                                                         max: 16,
                                                                                         summary: "Update ribbon smoothing"),
                                                               min: 1, max: 16, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-ribbon-uv-tiling", label: L("Ribbon UV Tiling"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.ribbonTextureTiling,
                                                                                    summary: "Update ribbon UV tiling"),
                                                               min: 0, max: 100, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-ribbon-uv-offset", label: L("Ribbon UV Offset"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.ribbonTextureOffset,
                                                                                    summary: "Update ribbon UV offset"),
                                                               min: -10_000, max: 10_000, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-render-alignment", label: L("Alignment"),
                                     value: .particleRenderAlignment(particleRenderAlignmentBinding(for: entity))),
                EditorInspectorField(id: "particle-velocity-stretch-scale", label: L("Velocity Stretch"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.renderer.velocityStretchScale,
                                                                                    summary: "Update velocity stretch"),
                                                               min: 0, max: 10, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-velocity-stretch-max", label: L("Max Stretch"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.renderer.velocityStretchMax,
                                                                                    summary: "Update max velocity stretch"),
                                                               min: 1, max: 100, step: 0.5, showsStepper: true)),
                EditorInspectorField(id: "particle-max-render-distance", label: L("Max Render Distance"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.renderer.maxRenderDistance,
                                                                                    summary: "Update particle render distance"),
                                                               min: 0, max: 100_000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-render-distance-fade", label: L("Distance Fade"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.renderer.renderDistanceFadeRange,
                                                                                    summary: "Update particle distance fade"),
                                                               min: 0, max: 100_000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-render-lod-start", label: L("LOD Start"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.renderer.renderLODStartDistance,
                                                                                    summary: "Update particle render LOD start"),
                                                               min: 0, max: 100_000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-render-lod-end", label: L("LOD End"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.renderer.renderLODEndDistance,
                                                                                    summary: "Update particle render LOD end"),
                                                               min: 0, max: 100_000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-render-lod-min-scale", label: L("LOD Min Scale"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.renderer.renderLODMinParticleScale,
                                                                                    summary: "Update particle render LOD scale"),
                                                               min: 0, max: 1, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-render-bounds-mode", label: L("Bounds Mode"),
                                     value: .particleRenderBoundsMode(particleRenderBoundsModeBinding(for: entity))),
                EditorInspectorField(id: "particle-render-bounds-radius", label: L("Manual Bounds"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.renderer.renderBoundsRadius,
                                                                                    summary: "Update particle render bounds"),
                                                               min: 0, max: 100_000, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-render-bounds-estimate", label: L("Auto Bounds"),
                                     value: .readOnly(format(scene.component(ParticleEmitter.self,
                                                                             for: entity)?
                                         .estimatedRenderBoundsRadius() ?? 0))),
                EditorInspectorField(id: "particle-texture", label: L("Texture"),
                                     value: .asset(particleTextureAssetBinding(for: entity),
                                                   acceptedKinds: [ImportableAssetKind.png.sceneKindLabel],
                                                   placeholder: L("Drop texture"))),
                EditorInspectorField(id: "particle-texture-sheet-columns", label: L("Sheet Columns"),
                                     value: .constrainedNumber(particleIntBinding(for: entity, \.settings.textureSheet.columns,
                                                                                  summary: "Update texture sheet columns"),
                                                               min: 1, max: 64, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-texture-sheet-rows", label: L("Sheet Rows"),
                                     value: .constrainedNumber(particleIntBinding(for: entity, \.settings.textureSheet.rows,
                                                                                  summary: "Update texture sheet rows"),
                                                               min: 1, max: 64, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-texture-sheet-frames", label: L("Sheet Frames"),
                                     value: .constrainedNumber(particleIntBinding(for: entity, \.settings.textureSheet.frameCount,
                                                                                  summary: "Update texture sheet frames"),
                                                               min: 1, max: 4096, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-texture-sheet-fps", label: L("Sheet FPS"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.textureSheet.frameRate,
                                                                                    summary: "Update texture sheet FPS"),
                                                               min: 0, max: 240, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-texture-sheet-playback", label: L("Sheet Playback"),
                                     value: .particleTextureSheetPlaybackMode(
                                         particleTextureSheetPlaybackModeBinding(for: entity)
                                     )),
                EditorInspectorField(id: "particle-texture-sheet-start-frame", label: L("Sheet Start"),
                                     value: .constrainedNumber(particleIntBinding(for: entity,
                                                                                  \.settings.textureSheet.startFrame,
                                                                                  summary: "Update texture sheet start frame"),
                                                               min: 0, max: 4095, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-texture-sheet-random", label: L("Sheet Random"),
                                     value: .constrainedNumber(particleIntBinding(for: entity,
                                                                                  \.settings.textureSheet.frameRandomness,
                                                                                  summary: "Update texture sheet random frames"),
                                                               min: 0, max: 4095, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-trail-length", label: L("Trail Length"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.trailLength,
                                                                                    summary: "Update particle trail length"),
                                                               min: 0, max: 10, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-trail-segments", label: L("Trail Segments"),
                                     value: .constrainedNumber(particleIntBinding(for: entity, \.settings.trails.trailSegments,
                                                                                  summary: "Update particle trail segments"),
                                                               min: 0, max: 64, step: 1, showsStepper: true)),
                EditorInspectorField(id: "particle-trail-end-size", label: L("Trail End Size"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.trailEndSizeScale,
                                                                                    summary: "Update particle trail end size"),
                                                               min: 0, max: 4, step: 0.05, showsStepper: true)),
                EditorInspectorField(id: "particle-trail-end-alpha", label: L("Trail End Alpha"),
                                     value: .constrainedNumber(particleFloatBinding(for: entity, \.settings.trails.trailEndAlphaScale,
                                                                                    summary: "Update particle trail end alpha"),
                                                               min: 0, max: 1, step: 0.05, showsStepper: true)),
            ]
        )
    }
}
