#ifndef GUAVA_NEXT_SDL3_SHIM_H
#define GUAVA_NEXT_SDL3_SHIM_H

#include <SDL3/SDL.h>

#if defined(__APPLE__)
#include <SDL3/SDL_metal.h>
#endif

// Window flags
enum {
	GUAVA_SDL_WINDOW_RESIZABLE = SDL_WINDOW_RESIZABLE,
	GUAVA_SDL_WINDOW_HIGH_PIXEL_DENSITY = SDL_WINDOW_HIGH_PIXEL_DENSITY,
	GUAVA_SDL_WINDOW_METAL = SDL_WINDOW_METAL,
};

// Application / window lifecycle events
enum {
	GUAVA_SDL_EVENT_QUIT = SDL_EVENT_QUIT,
	GUAVA_SDL_EVENT_WINDOW_RESIZED = SDL_EVENT_WINDOW_RESIZED,
	GUAVA_SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED = SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED,
	GUAVA_SDL_EVENT_WINDOW_METAL_VIEW_RESIZED = SDL_EVENT_WINDOW_METAL_VIEW_RESIZED,
	GUAVA_SDL_EVENT_WINDOW_CLOSE_REQUESTED = SDL_EVENT_WINDOW_CLOSE_REQUESTED,
	GUAVA_SDL_EVENT_WINDOW_DESTROYED = SDL_EVENT_WINDOW_DESTROYED,
	GUAVA_SDL_EVENT_WINDOW_EXPOSED = SDL_EVENT_WINDOW_EXPOSED,
	GUAVA_SDL_EVENT_WINDOW_MINIMIZED = SDL_EVENT_WINDOW_MINIMIZED,
	GUAVA_SDL_EVENT_WINDOW_RESTORED = SDL_EVENT_WINDOW_RESTORED,
	GUAVA_SDL_EVENT_WINDOW_FOCUS_GAINED = SDL_EVENT_WINDOW_FOCUS_GAINED,
	GUAVA_SDL_EVENT_WINDOW_FOCUS_LOST = SDL_EVENT_WINDOW_FOCUS_LOST,
	GUAVA_SDL_EVENT_WINDOW_OCCLUDED = SDL_EVENT_WINDOW_OCCLUDED,
};

// Keyboard events
enum {
	GUAVA_SDL_EVENT_KEY_DOWN = SDL_EVENT_KEY_DOWN,
	GUAVA_SDL_EVENT_KEY_UP   = SDL_EVENT_KEY_UP,
	GUAVA_SDL_EVENT_TEXT_INPUT = SDL_EVENT_TEXT_INPUT,
};

// Mouse events
enum {
	GUAVA_SDL_EVENT_MOUSE_MOTION      = SDL_EVENT_MOUSE_MOTION,
	GUAVA_SDL_EVENT_MOUSE_BUTTON_DOWN = SDL_EVENT_MOUSE_BUTTON_DOWN,
	GUAVA_SDL_EVENT_MOUSE_BUTTON_UP   = SDL_EVENT_MOUSE_BUTTON_UP,
	GUAVA_SDL_EVENT_MOUSE_WHEEL       = SDL_EVENT_MOUSE_WHEEL,
};

// Keyboard modifier masks (SDL_Keymod is typedef Uint16; #defines not imported by Swift)
enum {
	GUAVA_SDL_KMOD_LSHIFT = SDL_KMOD_LSHIFT,
	GUAVA_SDL_KMOD_RSHIFT = SDL_KMOD_RSHIFT,
	GUAVA_SDL_KMOD_LCTRL  = SDL_KMOD_LCTRL,
	GUAVA_SDL_KMOD_RCTRL  = SDL_KMOD_RCTRL,
	GUAVA_SDL_KMOD_LALT   = SDL_KMOD_LALT,
	GUAVA_SDL_KMOD_RALT   = SDL_KMOD_RALT,
	GUAVA_SDL_KMOD_LGUI   = SDL_KMOD_LGUI,
	GUAVA_SDL_KMOD_RGUI   = SDL_KMOD_RGUI,
};

// Mouse buttons (#defines not imported by Swift)
enum {
	GUAVA_SDL_BUTTON_LEFT   = SDL_BUTTON_LEFT,
	GUAVA_SDL_BUTTON_MIDDLE = SDL_BUTTON_MIDDLE,
	GUAVA_SDL_BUTTON_RIGHT  = SDL_BUTTON_RIGHT,
	GUAVA_SDL_BUTTON_X1     = SDL_BUTTON_X1,
	GUAVA_SDL_BUTTON_X2     = SDL_BUTTON_X2,
};

// Mouse wheel direction
enum {
	GUAVA_SDL_MOUSEWHEEL_FLIPPED = SDL_MOUSEWHEEL_FLIPPED,
};

#endif