#ifndef GUAVA_NEXT_SDL3_SHIM_H
#define GUAVA_NEXT_SDL3_SHIM_H

#include <SDL3/SDL.h>

#if defined(__APPLE__)
#include <SDL3/SDL_metal.h>
#endif

// Window flags
enum {
	GUAVA_SDL_WINDOW_RESIZABLE = SDL_WINDOW_RESIZABLE,
	GUAVA_SDL_WINDOW_HIGH_PIXEL_DENSITY = SDL_WINDOW_HIGH_PIXEL_DENSITY,
	GUAVA_SDL_WINDOW_METAL = SDL_WINDOW_METAL,
	GUAVA_SDL_WINDOW_BORDERLESS = SDL_WINDOW_BORDERLESS,
	GUAVA_SDL_WINDOW_MAXIMIZED = SDL_WINDOW_MAXIMIZED,
};

// Application / window lifecycle events
enum {
	GUAVA_SDL_EVENT_QUIT = SDL_EVENT_QUIT,
	GUAVA_SDL_EVENT_WINDOW_RESIZED = SDL_EVENT_WINDOW_RESIZED,
	GUAVA_SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED = SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED,
	GUAVA_SDL_EVENT_WINDOW_METAL_VIEW_RESIZED = SDL_EVENT_WINDOW_METAL_VIEW_RESIZED,
	GUAVA_SDL_EVENT_WINDOW_CLOSE_REQUESTED = SDL_EVENT_WINDOW_CLOSE_REQUESTED,
	GUAVA_SDL_EVENT_WINDOW_DESTROYED = SDL_EVENT_WINDOW_DESTROYED,
	GUAVA_SDL_EVENT_WINDOW_EXPOSED = SDL_EVENT_WINDOW_EXPOSED,
	GUAVA_SDL_EVENT_WINDOW_MINIMIZED = SDL_EVENT_WINDOW_MINIMIZED,
	GUAVA_SDL_EVENT_WINDOW_RESTORED = SDL_EVENT_WINDOW_RESTORED,
	GUAVA_SDL_EVENT_WINDOW_FOCUS_GAINED = SDL_EVENT_WINDOW_FOCUS_GAINED,
	GUAVA_SDL_EVENT_WINDOW_FOCUS_LOST = SDL_EVENT_WINDOW_FOCUS_LOST,
	GUAVA_SDL_EVENT_WINDOW_OCCLUDED = SDL_EVENT_WINDOW_OCCLUDED,
};

// Keyboard events
enum {
	GUAVA_SDL_EVENT_KEY_DOWN = SDL_EVENT_KEY_DOWN,
	GUAVA_SDL_EVENT_KEY_UP   = SDL_EVENT_KEY_UP,
	GUAVA_SDL_EVENT_TEXT_EDITING = SDL_EVENT_TEXT_EDITING,
	GUAVA_SDL_EVENT_TEXT_INPUT = SDL_EVENT_TEXT_INPUT,
};

// Mouse events
enum {
	GUAVA_SDL_EVENT_MOUSE_MOTION      = SDL_EVENT_MOUSE_MOTION,
	GUAVA_SDL_EVENT_MOUSE_BUTTON_DOWN = SDL_EVENT_MOUSE_BUTTON_DOWN,
	GUAVA_SDL_EVENT_MOUSE_BUTTON_UP   = SDL_EVENT_MOUSE_BUTTON_UP,
	GUAVA_SDL_EVENT_MOUSE_WHEEL       = SDL_EVENT_MOUSE_WHEEL,
};

// Keyboard modifier masks (SDL_Keymod is typedef Uint16; #defines not imported by Swift)
enum {
	GUAVA_SDL_KMOD_LSHIFT = SDL_KMOD_LSHIFT,
	GUAVA_SDL_KMOD_RSHIFT = SDL_KMOD_RSHIFT,
	GUAVA_SDL_KMOD_LCTRL  = SDL_KMOD_LCTRL,
	GUAVA_SDL_KMOD_RCTRL  = SDL_KMOD_RCTRL,
	GUAVA_SDL_KMOD_LALT   = SDL_KMOD_LALT,
	GUAVA_SDL_KMOD_RALT   = SDL_KMOD_RALT,
	GUAVA_SDL_KMOD_LGUI   = SDL_KMOD_LGUI,
	GUAVA_SDL_KMOD_RGUI   = SDL_KMOD_RGUI,
};

// Mouse buttons (#defines not imported by Swift)
enum {
	GUAVA_SDL_BUTTON_LEFT   = SDL_BUTTON_LEFT,
	GUAVA_SDL_BUTTON_MIDDLE = SDL_BUTTON_MIDDLE,
	GUAVA_SDL_BUTTON_RIGHT  = SDL_BUTTON_RIGHT,
	GUAVA_SDL_BUTTON_X1     = SDL_BUTTON_X1,
	GUAVA_SDL_BUTTON_X2     = SDL_BUTTON_X2,
};

// Mouse wheel direction
enum {
	GUAVA_SDL_MOUSEWHEEL_FLIPPED = SDL_MOUSEWHEEL_FLIPPED,
};

// Gamepad events
enum {
    GUAVA_SDL_EVENT_GAMEPAD_AXIS_MOTION = SDL_EVENT_GAMEPAD_AXIS_MOTION,
    GUAVA_SDL_EVENT_GAMEPAD_BUTTON_DOWN = SDL_EVENT_GAMEPAD_BUTTON_DOWN,
    GUAVA_SDL_EVENT_GAMEPAD_BUTTON_UP   = SDL_EVENT_GAMEPAD_BUTTON_UP,
    GUAVA_SDL_EVENT_GAMEPAD_ADDED       = SDL_EVENT_GAMEPAD_ADDED,
    GUAVA_SDL_EVENT_GAMEPAD_REMOVED     = SDL_EVENT_GAMEPAD_REMOVED,
};

// Audio subsystem constants (#define / pointer-cast macros not imported by Swift).
static const Uint32 GUAVA_SDL_INIT_AUDIO = SDL_INIT_AUDIO;
static const SDL_AudioDeviceID GUAVA_SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK = SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK;

// System cursor identifiers (SDL_SystemCursor enum is not imported as raw ints by Swift).
enum {
	GUAVA_SDL_SYSTEM_CURSOR_DEFAULT      = SDL_SYSTEM_CURSOR_DEFAULT,
	GUAVA_SDL_SYSTEM_CURSOR_TEXT         = SDL_SYSTEM_CURSOR_TEXT,
	GUAVA_SDL_SYSTEM_CURSOR_WAIT         = SDL_SYSTEM_CURSOR_WAIT,
	GUAVA_SDL_SYSTEM_CURSOR_CROSSHAIR    = SDL_SYSTEM_CURSOR_CROSSHAIR,
	GUAVA_SDL_SYSTEM_CURSOR_PROGRESS     = SDL_SYSTEM_CURSOR_PROGRESS,
	GUAVA_SDL_SYSTEM_CURSOR_NWSE_RESIZE  = SDL_SYSTEM_CURSOR_NWSE_RESIZE,
	GUAVA_SDL_SYSTEM_CURSOR_NESW_RESIZE  = SDL_SYSTEM_CURSOR_NESW_RESIZE,
	GUAVA_SDL_SYSTEM_CURSOR_EW_RESIZE    = SDL_SYSTEM_CURSOR_EW_RESIZE,
	GUAVA_SDL_SYSTEM_CURSOR_NS_RESIZE    = SDL_SYSTEM_CURSOR_NS_RESIZE,
	GUAVA_SDL_SYSTEM_CURSOR_MOVE         = SDL_SYSTEM_CURSOR_MOVE,
	GUAVA_SDL_SYSTEM_CURSOR_NOT_ALLOWED  = SDL_SYSTEM_CURSOR_NOT_ALLOWED,
	GUAVA_SDL_SYSTEM_CURSOR_POINTER      = SDL_SYSTEM_CURSOR_POINTER,
};

#endif  // GUAVA_NEXT_SDL3_SHIM_H
