import Foundation
import SIMDCompat

/// CPU-baked studio environment for image-based lighting, prefiltered the way
/// real engines do it (learnopengl / Karis split-sum, as used by UE & Godot):
/// the specular mip chain is generated by **GGX importance sampling** of the
/// environment per roughness level (not a box blur), so reflections blur
/// physically with roughness. mip 0 is the sharp mirror, mip N is roughness
/// N/(mipCount-1), and the most-blurred mip doubles as diffuse irradiance.
/// Stored as an equirectangular rgba16Float texture; a dark studio with bright
/// HDR soft-boxes is what makes polished metal read as gunmetal/chrome.
enum StudioEnvironmentIBL {
    static let baseWidth = 512
    static let baseHeight = 256
    static let mipCount = 6          // roughness 0 … 1 across the chain
    static let maxLOD: Float = 5.0   // mipCount - 1
    static let prefilterSamples = 32

    struct MipLevel {
        let width: Int
        let height: Int
        let halfRGBA: [UInt16]
    }

    static func generate() -> [MipLevel] {
        var levels: [MipLevel] = []
        for level in 0..<mipCount {
            let w = max(1, baseWidth >> level)
            let h = max(1, baseHeight >> level)
            let roughness = Float(level) / Float(mipCount - 1)
            var half = [UInt16](repeating: 0, count: w * h * 4)
            for y in 0..<h {
                for x in 0..<w {
                    let u = (Float(x) + 0.5) / Float(w)
                    let v = (Float(y) + 0.5) / Float(h)
                    let dir = direction(u: u, v: v)
                    let c = level == 0 ? radiance(forDirection: dir)
                                       : prefilter(normal: dir, roughness: roughness)
                    let i = (y * w + x) * 4
                    half[i + 0] = floatToHalf(c.x)
                    half[i + 1] = floatToHalf(c.y)
                    half[i + 2] = floatToHalf(c.z)
                    half[i + 3] = floatToHalf(1.0)
                }
            }
            levels.append(MipLevel(width: w, height: h, halfRGBA: half))
        }
        return levels
    }

    // MARK: - GGX prefilter (split-sum specular IBL)

    /// Prefilter the environment around `normal` for `roughness`, integrating the
    /// GGX specular lobe via importance sampling (Karis 2013 / learnopengl).
    private static func prefilter(normal N: SIMD3<Float>, roughness: Float) -> SIMD3<Float> {
        let V = N // common N=V=R assumption for prefiltering
        var color = SIMD3<Float>.zero
        var totalWeight: Float = 0
        for i in 0..<prefilterSamples {
            let xi = hammersley(i, prefilterSamples)
            let H = importanceSampleGGX(xi, N: N, roughness: roughness)
            let L = simd_normalize(2.0 * simd_dot(V, H) * H - V)
            let nDotL = simd_dot(N, L)
            if nDotL > 0 {
                color += radiance(forDirection: L) * nDotL
                totalWeight += nDotL
            }
        }
        return totalWeight > 0 ? color / totalWeight : radiance(forDirection: N)
    }

    private static func radicalInverseVdC(_ bits: UInt32) -> Float {
        var b = bits
        b = (b << 16) | (b >> 16)
        b = ((b & 0x5555_5555) << 1) | ((b & 0xAAAA_AAAA) >> 1)
        b = ((b & 0x3333_3333) << 2) | ((b & 0xCCCC_CCCC) >> 2)
        b = ((b & 0x0F0F_0F0F) << 4) | ((b & 0xF0F0_F0F0) >> 4)
        b = ((b & 0x00FF_00FF) << 8) | ((b & 0xFF00_FF00) >> 8)
        return Float(b) * 2.328_306_4e-10
    }

    private static func hammersley(_ i: Int, _ n: Int) -> SIMD2<Float> {
        SIMD2<Float>(Float(i) / Float(n), radicalInverseVdC(UInt32(i)))
    }

    private static func importanceSampleGGX(_ xi: SIMD2<Float>,
                                            N: SIMD3<Float>,
                                            roughness: Float) -> SIMD3<Float> {
        let a = roughness * roughness
        let phi = 2.0 * Float.pi * xi.x
        let cosTheta = sqrt((1.0 - xi.y) / (1.0 + (a * a - 1.0) * xi.y))
        let sinTheta = sqrt(max(0.0, 1.0 - cosTheta * cosTheta))
        // Half-vector in tangent space, then to world around N.
        let hT = SIMD3<Float>(cos(phi) * sinTheta, sin(phi) * sinTheta, cosTheta)
        let up = abs(N.z) < 0.999 ? SIMD3<Float>(0, 0, 1) : SIMD3<Float>(1, 0, 0)
        let tangent = simd_normalize(simd_cross(up, N))
        let bitangent = simd_cross(N, tangent)
        return simd_normalize(tangent * hT.x + bitangent * hT.y + N * hT.z)
    }

    // MARK: - Environment definition

    /// Equirect (u, v) → world direction. Matches `equirect_uv` in mesh.wgsl.
    private static func direction(u: Float, v: Float) -> SIMD3<Float> {
        let phi = (u - 0.5) * 2.0 * Float.pi
        let theta = v * Float.pi
        let sinTheta = sin(theta)
        return SIMD3<Float>(sinTheta * cos(phi), cos(theta), sinTheta * sin(phi))
    }

    private static func radiance(forDirection dir: SIMD3<Float>) -> SIMD3<Float> {
        // BRIGHT, fairly even studio so the material is clearly visible — this is
        // an asset viewer (Sketchfab/UE preview), not a dark glamour shot. A
        // mirror metal reflects this, so a bright dome makes the body read as a
        // legible mid-tone metal rather than a black void, while a soft top→floor
        // gradient + soft-boxes keep enough directional variation to read as
        // metal and provide bright highlights.
        // Studio with REAL vertical contrast — a dim floor brightening to a lit
        // ceiling. A uniform dome makes glossy metal a flat grey ("white model");
        // this gradient gives a clear dark-underside / bright-top reflection so
        // the metal reads as a 3D reflective object, plus a big bright key
        // soft-box as the dominant highlight (the hallmark of polished metal).
        let y = dir.y
        let floorColor = SIMD3<Float>(0.05, 0.05, 0.055)
        let horizonColor = SIMD3<Float>(0.22, 0.225, 0.245)
        let ceilColor = SIMD3<Float>(0.55, 0.565, 0.62)
        var c: SIMD3<Float>
        if y >= 0 {
            c = horizonColor + (ceilColor - horizonColor) * smoothstep(0.0, 1.0, y)
        } else {
            c = horizonColor + (floorColor - horizonColor) * smoothstep(0.0, 1.0, -y)
        }
        // Large bright key soft-box (broad → a big soft reflection) + fills.
        c += softbox(dir, simd_normalize(SIMD3<Float>(0.35, 0.50, 0.75)), 0.74, 0.93,
                     SIMD3<Float>(15.0, 15.0, 14.0))  // key (broad, bright)
        c += softbox(dir, simd_normalize(SIMD3<Float>(-0.62, 0.42, 0.20)), 0.88, 0.97,
                     SIMD3<Float>(3.2, 3.5, 4.2))     // fill (cool)
        c += softbox(dir, simd_normalize(SIMD3<Float>(0.10, 0.32, -0.92)), 0.90, 0.98,
                     SIMD3<Float>(4.2, 3.9, 3.4))     // rim (warm)
        return c
    }

    private static func softbox(_ dir: SIMD3<Float>,
                                _ center: SIMD3<Float>,
                                _ inner: Float,
                                _ outer: Float,
                                _ color: SIMD3<Float>) -> SIMD3<Float> {
        color * smoothstep(inner, outer, simd_dot(dir, center))
    }

    private static func smoothstep(_ edge0: Float, _ edge1: Float, _ x: Float) -> Float {
        let t = max(0, min(1, (x - edge0) / max(edge1 - edge0, 1e-5)))
        return t * t * (3 - 2 * t)
    }

    // MARK: - Half-float packing

    /// IEEE-754 binary32 → binary16 for the positive HDR values here.
    static func floatToHalf(_ value: Float) -> UInt16 {
        let bits = value.bitPattern
        let sign = UInt16((bits >> 16) & 0x8000)
        let exponent = Int((bits >> 23) & 0xFF) - 127 + 15
        let mantissa = bits & 0x007F_FFFF
        if exponent <= 0 { return sign }
        if exponent >= 31 { return sign | 0x7C00 }
        return sign | UInt16(exponent << 10) | UInt16(mantissa >> 13)
    }
}
