import Foundation
import SIMDCompat

/// Authored settings for an entity backed by a pre-fractured asset.
public struct Destructible: RuntimeComponent, Sendable, Equatable {
    public var assetResourceID: String
    public var damageThreshold: Float
    public var impulseThreshold: Float
    public var fragmentBudget: Int
    public var maximumFragmentLifetimeSeconds: Float
    public var sleepingRecycleDelaySeconds: Float
    public var separationImpulse: Float
    public var isEnabled: Bool

    public init(
        assetResourceID: String = "",
        damageThreshold: Float = 100,
        impulseThreshold: Float = 10,
        fragmentBudget: Int = 256,
        maximumFragmentLifetimeSeconds: Float = 30,
        sleepingRecycleDelaySeconds: Float = 5,
        separationImpulse: Float = 0.05,
        isEnabled: Bool = true
    ) {
        self.assetResourceID = assetResourceID
        self.damageThreshold = max(0, damageThreshold)
        self.impulseThreshold = max(0, impulseThreshold)
        self.fragmentBudget = max(0, fragmentBudget)
        self.maximumFragmentLifetimeSeconds = max(0, maximumFragmentLifetimeSeconds)
        self.sleepingRecycleDelaySeconds = max(0, sleepingRecycleDelaySeconds)
        self.separationImpulse = max(0, separationImpulse)
        self.isEnabled = isEnabled
    }
}

/// One convex piece generated by the pre-fracture asset pipeline.
public struct DestructibleFragmentAsset: Sendable, Equatable {
    public var fragmentID: UInt32
    public var colliderResourceID: String
    public var localTransform: LocalTransform
    public var mass: Float
    public var renderMesh: RenderMeshComponent?
    public var renderMaterial: RenderMaterialComponent?

    public init(
        fragmentID: UInt32,
        colliderResourceID: String,
        localTransform: LocalTransform = .identity,
        mass: Float = 1,
        renderMesh: RenderMeshComponent? = nil,
        renderMaterial: RenderMaterialComponent? = nil
    ) {
        self.fragmentID = fragmentID
        self.colliderResourceID = colliderResourceID
        self.localTransform = localTransform
        self.mass = max(0.0001, mass)
        self.renderMesh = renderMesh
        self.renderMaterial = renderMaterial
    }
}

/// A breakable edge in the imported fragment connection graph. A zero threshold
/// inherits the corresponding entity-level threshold from `Destructible`.
public struct DestructibleConnectionAsset: Sendable, Equatable {
    public var connectionID: UInt32
    public var fragmentA: UInt32
    public var fragmentB: UInt32
    public var damageThreshold: Float
    public var impulseThreshold: Float

    public init(
        connectionID: UInt32,
        fragmentA: UInt32,
        fragmentB: UInt32,
        damageThreshold: Float = 0,
        impulseThreshold: Float = 0
    ) {
        self.connectionID = connectionID
        self.fragmentA = fragmentA
        self.fragmentB = fragmentB
        self.damageThreshold = max(0, damageThreshold)
        self.impulseThreshold = max(0, impulseThreshold)
    }
}

/// Runtime-ready product of pre-fracture import. Convex geometry is resolved through
/// `MeshColliderGeometryResource`, so it shares the normal shape bake cache.
public struct DestructibleAsset: Sendable, Equatable {
    public var revision: UInt64
    public var fragments: [DestructibleFragmentAsset]
    public var connections: [DestructibleConnectionAsset]

    public init(
        revision: UInt64 = 0,
        fragments: [DestructibleFragmentAsset],
        connections: [DestructibleConnectionAsset] = []
    ) {
        self.revision = revision
        self.fragments = fragments.sorted { $0.fragmentID < $1.fragmentID }
        self.connections = connections.sorted { $0.connectionID < $1.connectionID }
    }
}

public struct DestructibleAssetResource: Sendable, Equatable {
    public var assetsByResourceID: [String: DestructibleAsset]

    public init(assetsByResourceID: [String: DestructibleAsset] = [:]) {
        self.assetsByResourceID = assetsByResourceID
    }

    public func asset(for resourceID: String) -> DestructibleAsset? {
        assetsByResourceID[resourceID]
    }
}

public struct DestructionSettingsResource: Sendable, Equatable {
    public var maximumActiveFragmentCount: Int
    public var maximumEventCountPerFrame: Int

    public init(
        maximumActiveFragmentCount: Int = 4_096,
        maximumEventCountPerFrame: Int = 1_024
    ) {
        self.maximumActiveFragmentCount = max(0, maximumActiveFragmentCount)
        self.maximumEventCountPerFrame = max(1, maximumEventCountPerFrame)
    }
}

public struct DestructionCommand: Sendable, Equatable {
    public var entity: EntityID
    public var damage: Float
    public var impulse: SIMD3<Float>
    public var worldPoint: SIMD3<Float>?
    public var forceFracture: Bool

    public init(
        entity: EntityID,
        damage: Float = 0,
        impulse: SIMD3<Float> = .zero,
        worldPoint: SIMD3<Float>? = nil,
        forceFracture: Bool = false
    ) {
        self.entity = entity
        self.damage = max(0, damage)
        self.impulse = impulse
        self.worldPoint = worldPoint
        self.forceFracture = forceFracture
    }
}

public struct DestructionCommandFrameResource: Sendable, Equatable {
    public var commands: [DestructionCommand]

    public init(commands: [DestructionCommand] = []) {
        self.commands = commands
    }

    public static let empty = DestructionCommandFrameResource()
}

public enum DestructionCause: String, Sendable, Equatable {
    case forced
    case damage
    case contactImpulse
    case connectionBreak
}

public struct DestructionEvent: Sendable, Equatable {
    public var sourceEntity: EntityID
    public var cause: DestructionCause
    public var fragmentEntities: [EntityID]
    public var fragmentIDs: [UInt32]
    public var brokenConnectionIDs: [UInt32]
    public var appliedDamage: Float
    public var appliedImpulse: Float
    public var droppedFragmentCount: Int

    public init(
        sourceEntity: EntityID,
        cause: DestructionCause,
        fragmentEntities: [EntityID],
        fragmentIDs: [UInt32],
        brokenConnectionIDs: [UInt32],
        appliedDamage: Float,
        appliedImpulse: Float,
        droppedFragmentCount: Int = 0
    ) {
        self.sourceEntity = sourceEntity
        self.cause = cause
        self.fragmentEntities = fragmentEntities
        self.fragmentIDs = fragmentIDs
        self.brokenConnectionIDs = brokenConnectionIDs
        self.appliedDamage = appliedDamage
        self.appliedImpulse = appliedImpulse
        self.droppedFragmentCount = max(0, droppedFragmentCount)
    }
}

public enum DestructionFailureReason: String, Sendable, Equatable {
    case invalidConfiguration
    case invalidCommand
    case missingAsset
    case invalidAsset
    case fragmentBudgetExhausted
}

public struct DestructionFailureEvent: Sendable, Equatable {
    public var sourceEntity: EntityID
    public var reason: DestructionFailureReason
    public var message: String

    public init(sourceEntity: EntityID, reason: DestructionFailureReason, message: String) {
        self.sourceEntity = sourceEntity
        self.reason = reason
        self.message = message
    }
}

public enum DestructionRecycleReason: String, Sendable, Equatable {
    case lifetimeExpired
    case sleeping
    case sourceRemoved
}

public struct DestructionRecycleEvent: Sendable, Equatable {
    public var sourceEntity: EntityID
    public var fragmentEntity: EntityID
    public var fragmentID: UInt32
    public var reason: DestructionRecycleReason

    public init(
        sourceEntity: EntityID,
        fragmentEntity: EntityID,
        fragmentID: UInt32,
        reason: DestructionRecycleReason
    ) {
        self.sourceEntity = sourceEntity
        self.fragmentEntity = fragmentEntity
        self.fragmentID = fragmentID
        self.reason = reason
    }
}

public struct DestructionEventFrameResource: Sendable, Equatable {
    public var events: [DestructionEvent]
    public var failures: [DestructionFailureEvent]
    public var recycledFragments: [DestructionRecycleEvent]
    public var didOverflow: Bool

    public init(
        events: [DestructionEvent] = [],
        failures: [DestructionFailureEvent] = [],
        recycledFragments: [DestructionRecycleEvent] = [],
        didOverflow: Bool = false
    ) {
        self.events = events
        self.failures = failures
        self.recycledFragments = recycledFragments
        self.didOverflow = didOverflow
    }

    public static let empty = DestructionEventFrameResource()
}

public struct DestructionSourceState: Sendable, Equatable {
    public var sourceEntity: EntityID
    public var hasFractured: Bool
    public var accumulatedDamage: Float
    public var brokenConnectionIDs: [UInt32]
    public var activeFragmentEntities: [EntityID]
    public var activeFragmentIDs: [UInt32]

    public init(
        sourceEntity: EntityID,
        hasFractured: Bool = false,
        accumulatedDamage: Float = 0,
        brokenConnectionIDs: [UInt32] = [],
        activeFragmentEntities: [EntityID] = [],
        activeFragmentIDs: [UInt32] = []
    ) {
        self.sourceEntity = sourceEntity
        self.hasFractured = hasFractured
        self.accumulatedDamage = accumulatedDamage
        self.brokenConnectionIDs = brokenConnectionIDs
        self.activeFragmentEntities = activeFragmentEntities
        self.activeFragmentIDs = activeFragmentIDs
    }
}

public struct DestructionStateFrameResource: Sendable, Equatable {
    public var sources: [EntityID: DestructionSourceState]

    public init(sources: [EntityID: DestructionSourceState] = [:]) {
        self.sources = sources
    }

    public var activeFragmentCount: Int {
        sources.values.reduce(0) { $0 + $1.activeFragmentEntities.count }
    }

    public static let empty = DestructionStateFrameResource()
}

/// Runtime ownership marker. Authored Scene and Prefab documents omit fragment
/// entities, while GameSave snapshots preserve this ownership with remapped IDs.
public struct DestructibleFragment: RuntimeComponent, Sendable, Equatable {
    public var sourceEntity: EntityID
    public var fragmentID: UInt32
    public var spawnedAtSeconds: Double
    public var maximumLifetimeSeconds: Float
    public var sleepingRecycleDelaySeconds: Float

    public init(
        sourceEntity: EntityID,
        fragmentID: UInt32,
        spawnedAtSeconds: Double,
        maximumLifetimeSeconds: Float,
        sleepingRecycleDelaySeconds: Float
    ) {
        self.sourceEntity = sourceEntity
        self.fragmentID = fragmentID
        self.spawnedAtSeconds = spawnedAtSeconds
        self.maximumLifetimeSeconds = max(0, maximumLifetimeSeconds)
        self.sleepingRecycleDelaySeconds = max(0, sleepingRecycleDelaySeconds)
    }
}

struct DestructionRuntimeSourceState: Sendable, Equatable {
    var hasFractured = false
    var accumulatedDamage: Float = 0
    var brokenConnectionIDs: Set<UInt32> = []
    var hasAuthoredSourceSnapshot = false
    var authoredRigidBody: RigidBody?
    var authoredCollider: Collider?
    var authoredRenderMesh: RenderMeshComponent?
}

struct DestructionRuntimeStateResource: Sendable, Equatable {
    var elapsedSeconds: Double = 0
    var sources: [EntityID: DestructionRuntimeSourceState] = [:]
    var sleepingSinceByFragment: [EntityID: Double] = [:]
}
