//! Render graph infrastructure for managing rendering pass dependencies and resource lifetimes.
//!
//! The RenderGraph implements a modern render graph architecture that decouples rendering logic
//! into isolated passes (e.g., shadow_map, depth_prepass, base_pass, post_process). The compile()
//! algorithm performs topological sorting, tracks resource access patterns, and calculates per-resource
//! lifetimes (first_use_pass, last_use_pass) to enable efficient GPU memory management.
//!
//! Key concepts:
//! - Resources: GPU textures/buffers (shadow maps, depth buffers, screen-space targets) identified
//!   by ResourceKind. Can be transient (temporary, freed between frames) or persistent (e.g., swapchain).
//! - Passes: Rendering workloads (graphics/compute/copy queues) that read input resources and
//!   write output resources. Each pass declares its inputs/outputs and queue class.
//! - Dependencies: Implicit barriers generated by compile() when a resource transitions from
//!   read→write or write→read between passes. Cross-queue dependencies are tracked separately.
//! - Lifetimes: Calculated to determine memory pressure; resource is valid from first_use_pass
//!   until last_use_pass. Transient resources can be freed after last_use_pass.
//!
//! Thread-safety: Not thread-safe. Compile must complete before rendering begins.

const std = @import("std");

/// GPU queue type for pass execution.
pub const QueueClass = enum {
    /// Graphics queue: rasterization, rendering to targets.
    graphics,
    /// Compute queue: compute shaders, parallel algorithms.
    compute,
    /// Copy queue: data transfers, texture uploads.
    copy,
};

/// Semantic category of a rendering pass. Used for debugging, serialization, and conditional execution.
pub const PassKind = enum {
    /// Shadow map generation for directional/spot lights.
    shadow_map,
    /// Depth prepass: outputs only depth for early-z optimization.
    depth_prepass,
    /// Object ID pass: renders entity IDs for mouse picking/selection.
    id_pass,
    /// Main opaque geometry pass: shades with PBR/IBL.
    base_pass,
    /// Skybox/background environment pass.
    skybox_pass,
    /// Deferred lighting pass: consume G-buffer, produce lit color.
    lighting,
    /// Transparent geometry pass: depth-sorted alpha blending.
    transparent,
    /// Post-processing effects: FXAA, bloom, DOF, SSR, SSAO.
    post_process,
    /// Tone mapping: convert HDR to SDR for display.
    tonemap_pass,
    /// Outline/selection rendering.
    outline_pass,
    /// Gizmo/debug geometry overlay (not occluded by scene).
    gizmo_overlay,
    /// UI overlay (always on top).
    ui_overlay,
};

/// GPU resource type tracked by the render graph.
pub const ResourceKind = enum {
    /// Shadow depth map (typically 2048x2048 d32_float, sized for GPU memory budget).
    shadow_map,
    /// Depth buffer (d32_float or d24s8).
    depth,
    /// Object ID buffer (r32uint): encodes entity ID for picking.
    id_buffer,
    /// Opaque scene color target before lighting (e.g., RGBA8_UNORM or RGBA16_FLOAT for HDR).
    scene_color,
    /// Lit scene color after lighting pass (includes indirect/IBL contribution).
    lit_color,
    /// Post-process working buffer (bloom downsample, SSAO, SSR output).
    post_color,
    /// Final backbuffer/swapchain image presented to screen.
    swapchain,
};

/// Access pattern for a resource within a pass.
pub const ResourceAccess = enum {
    /// Input resource: barriers enforce previous writes complete before this pass reads.
    read,
    /// Output resource: barriers enforce this pass completes before subsequent reads/writes.
    write,
    /// Read and write (rare): resource is both input and output; used for in-place modify operations.
    read_write,

    /// Returns true if this access pattern includes writes (write or read_write).
    pub fn writes(self: ResourceAccess) bool {
        return self == .write or self == .read_write;
    }
};

/// GPU resource descriptor in the graph.
pub const ResourceNode = struct {
    /// Debug name for debugging/logging.
    name: []const u8,
    /// Type of GPU resource (shadow map, depth buffer, color target, etc.).
    kind: ResourceKind,
    /// true: resource lifetime managed externally (e.g., swapchain owned by window system).
    external: bool = false,
    /// true: resource can be freed after last use within a frame; false: persistent across frames.
    transient: bool = true,
};

/// Resource usage descriptor: which resource and how a pass accesses it.
pub const PassResourceUse = struct {
    /// Index into RenderGraph.resources array.
    resource: u16,
    /// Read, write, or read-write access.
    access: ResourceAccess,
};

/// Declarative rendering pass descriptor. User populates this; compile() generates execution order.
pub const RenderPass = struct {
    /// Debug name for logging and debugging.
    name: []const u8,
    /// Semantic category (shadow_map, base_pass, post_process, etc.).
    kind: PassKind,
    /// GPU queue to execute on (graphics, compute, or copy).
    queue: QueueClass = .graphics,
    /// If false, compile() skips this pass entirely.
    enabled: bool = true,
    /// Resources read by this pass; compile() adds input barriers if previous passes wrote them.
    inputs: []const PassResourceUse = &.{},
    /// Resources written by this pass; compile() adds output barriers for subsequent readers.
    outputs: []const PassResourceUse = &.{},
};

/// Explicit dependency edge calculated by compile() between two passes.
pub const DependencyEdge = struct {
    /// Producer pass index (writes the resource).
    from_pass: u16,
    /// Consumer pass index (reads the resource).
    to_pass: u16,
    /// Resource causing the dependency.
    resource: u16,
    /// How the producer accesses the resource (usually write).
    previous_access: ResourceAccess,
    /// How the consumer accesses the resource (usually read).
    next_access: ResourceAccess,
    /// true if passes execute on different queues; requires queue synchronization primitive.
    cross_queue: bool,
};

/// Calculated lifetime of a resource: valid from first_use_pass to last_use_pass.
pub const ResourceLifetime = struct {
    /// Index into RenderGraph.resources array.
    resource: u16,
    /// Earliest pass that reads or writes this resource (null if unused).
    first_use_pass: ?u16 = null,
    /// Latest pass that reads or writes this resource (null if unused).
    last_use_pass: ?u16 = null,
};

/// Compiled pass ready for execution: includes input/output resources, execution order, and dependency count.
pub const CompiledPass = struct {
    /// Index of this pass in execution order (0..enabled_pass_count-1).
    pass_index: u16,
    /// Debug name from original RenderPass.
    name: []const u8,
    /// Pass semantic category.
    kind: PassKind,
    /// Queue this pass executes on.
    queue: QueueClass,
    /// Input resources with read access semantics.
    inputs: []const PassResourceUse,
    /// Output resources with write access semantics.
    outputs: []const PassResourceUse,
    /// Number of other passes this pass depends on (for topological ordering). Must reach 0 before executing.
    dependency_count: usize,
};

pub const BarrierState = enum {
    unknown,
    shader_read,
    shader_write,
    shader_read_write,
    present,
};

pub const BarrierPlan = struct {
    from_pass: u16,
    to_pass: u16,
    resource: u16,
    src_state: BarrierState,
    dst_state: BarrierState,
    cross_queue: bool,
};

pub const PassExecutionStat = struct {
    name: []const u8,
    kind: PassKind,
    queue: QueueClass,
    input_count: usize,
    output_count: usize,
    dependency_count: usize,
    cpu_time_ns: u64 = 0,
    draw_calls: usize = 0,
    triangles_drawn: usize = 0,
};

const AccessState = struct {
    pass: u16,
    access: ResourceAccess,
    queue: QueueClass,
};

const GraphJson = struct {
    resources: []const ResourceNode,
    passes: []const CompiledPass,
    dependencies: []const DependencyEdge,
    lifetimes: []const ResourceLifetime,
};

const GraphReport = struct {
    backend: []const u8,
    draw_calls: usize,
    triangles_drawn: usize,
    resource_count: usize,
    pass_count: usize,
    passes: []const PassExecutionStat,
    lifetimes: []const ResourceLifetime,
};

pub const CompiledGraph = struct {
    allocator: std.mem.Allocator,
    execution: []CompiledPass,
    dependencies: []DependencyEdge,
    resource_lifetimes: []ResourceLifetime,

    pub fn deinit(self: *CompiledGraph) void {
        self.allocator.free(self.execution);
        self.allocator.free(self.dependencies);
        self.allocator.free(self.resource_lifetimes);
        self.* = undefined;
    }
};

pub const RenderGraph = struct {
    allocator: std.mem.Allocator,
    resources: std.ArrayList(ResourceNode) = .empty,
    passes: std.ArrayList(RenderPass) = .empty,
    compiled: ?CompiledGraph = null,

    pub fn init(allocator: std.mem.Allocator) RenderGraph {
        return .{ .allocator = allocator };
    }

    pub fn initDefault3D(allocator: std.mem.Allocator) !RenderGraph {
        var graph = RenderGraph.init(allocator);
        try graph.resetToDefault3D();
        return graph;
    }

    pub fn deinit(self: *RenderGraph) void {
        if (self.compiled) |*compiled| {
            compiled.deinit();
        }
        for (self.passes.items) |*pass| {
            self.allocator.free(pass.inputs);
            self.allocator.free(pass.outputs);
        }
        self.passes.deinit(self.allocator);
        self.resources.deinit(self.allocator);
    }

    pub fn resetToDefault3D(self: *RenderGraph) !void {
        if (self.compiled) |*compiled| {
            compiled.deinit();
            self.compiled = null;
        }
        for (self.passes.items) |*pass| {
            self.allocator.free(pass.inputs);
            self.allocator.free(pass.outputs);
        }
        self.passes.clearRetainingCapacity();
        self.resources.clearRetainingCapacity();

        const shadow_map = try self.addResource(.{ .name = "ShadowMap", .kind = .shadow_map });
        const scene_depth = try self.addResource(.{ .name = "SceneDepth", .kind = .depth });
        const entity_id = try self.addResource(.{ .name = "EntityId", .kind = .id_buffer });
        const scene_color = try self.addResource(.{ .name = "SceneColor", .kind = .scene_color });
        const lit_color = try self.addResource(.{ .name = "LitColor", .kind = .lit_color });
        const post_color = try self.addResource(.{ .name = "PostColor", .kind = .post_color });
        const swapchain = try self.addResource(.{ .name = "Swapchain", .kind = .swapchain, .external = true, .transient = false });

        try self.addPass(.{
            .name = "ShadowMap",
            .kind = .shadow_map,
            .outputs = &.{.{ .resource = shadow_map, .access = .write }},
        });
        try self.addPass(.{
            .name = "DepthPrepass",
            .kind = .depth_prepass,
            .outputs = &.{.{ .resource = scene_depth, .access = .write }},
        });
        try self.addPass(.{
            .name = "IDPass",
            .kind = .id_pass,
            .inputs = &.{.{ .resource = scene_depth, .access = .read }},
            .outputs = &.{.{ .resource = entity_id, .access = .write }},
        });
        try self.addPass(.{
            .name = "BasePass",
            .kind = .base_pass,
            .inputs = &.{.{ .resource = scene_depth, .access = .read }},
            .outputs = &.{.{ .resource = scene_color, .access = .write }},
        });
        try self.addPass(.{
            .name = "Lighting",
            .kind = .lighting,
            .inputs = &.{
                .{ .resource = shadow_map, .access = .read },
                .{ .resource = scene_depth, .access = .read },
                .{ .resource = scene_color, .access = .read },
            },
            .outputs = &.{.{ .resource = lit_color, .access = .write }},
        });
        try self.addPass(.{
            .name = "Transparent",
            .kind = .transparent,
            .inputs = &.{
                .{ .resource = lit_color, .access = .read },
                .{ .resource = scene_depth, .access = .read },
            },
            .outputs = &.{.{ .resource = lit_color, .access = .read_write }},
        });
        try self.addPass(.{
            .name = "PostProcess",
            .kind = .post_process,
            .inputs = &.{.{ .resource = lit_color, .access = .read }},
            .outputs = &.{.{ .resource = post_color, .access = .write }},
        });
        try self.addPass(.{
            .name = "OutlinePass",
            .kind = .outline_pass,
            .inputs = &.{
                .{ .resource = entity_id, .access = .read },
                .{ .resource = post_color, .access = .read },
            },
            .outputs = &.{.{ .resource = post_color, .access = .read_write }},
        });
        try self.addPass(.{
            .name = "GizmoPass",
            .kind = .gizmo_overlay,
            .inputs = &.{.{ .resource = post_color, .access = .read }},
            .outputs = &.{.{ .resource = post_color, .access = .read_write }},
        });
        try self.addPass(.{
            .name = "UIOverlay",
            .kind = .ui_overlay,
            .inputs = &.{.{ .resource = post_color, .access = .read }},
            .outputs = &.{.{ .resource = swapchain, .access = .write }},
        });

        try self.compile();
    }

    pub fn addResource(self: *RenderGraph, resource: ResourceNode) !u16 {
        try self.resources.append(self.allocator, resource);
        return @intCast(self.resources.items.len - 1);
    }

    pub fn addPass(self: *RenderGraph, pass: RenderPass) !void {
        try self.passes.append(self.allocator, .{
            .name = pass.name,
            .kind = pass.kind,
            .queue = pass.queue,
            .enabled = pass.enabled,
            .inputs = try self.allocator.dupe(PassResourceUse, pass.inputs),
            .outputs = try self.allocator.dupe(PassResourceUse, pass.outputs),
        });
    }

    /// Topologically compiles the render graph into an execution plan.
    ///
    /// Algorithm:
    /// 1. Iterate enabled passes in declaration order.
    /// 2. For each pass, track resource accesses (inputs + outputs).
    /// 3. For each resource, look at last access (if any):
    ///    a. If previous pass is different and last access has different queue: add cross-queue dependency.
    ///    b. If previous pass wrote and current pass reads: add read-after-write dependency.
    ///    c. If previous pass read and current pass writes: add write-after-read dependency.
    ///    d. If both read/write: depends on access patterns (RAW, WAR, WAW).
    /// 4. Record last_access for this resource/pass for next pass to check.
    /// 5. Calculate resource lifetimes: first_use_pass, last_use_pass.
    ///
    /// Output: generates CompiledGraph with execution order, dependency edges, and lifetimes.
    /// This allows GPU drivers to insert memory barriers and queue synchronization.
    pub fn compile(self: *RenderGraph) !void {
        // Clean up previous compile if present
        if (self.compiled) |*compiled| {
            compiled.deinit();
            self.compiled = null;
        }

        // Collect only enabled passes; skip disabled ones completely
        var enabled_passes = std.ArrayList(CompiledPass).empty;
        defer enabled_passes.deinit(self.allocator);

        // Accumulate dependency edges between passes (transitions requiring barriers)
        var dependencies = std.ArrayList(DependencyEdge).empty;
        defer dependencies.deinit(self.allocator);

        // Track per-resource lifetime: first_use_pass and last_use_pass
        const resource_lifetimes = try self.allocator.alloc(ResourceLifetime, self.resources.items.len);
        errdefer self.allocator.free(resource_lifetimes);
        for (resource_lifetimes, 0..) |*lifetime, index| {
            lifetime.* = .{ .resource = @intCast(index) };
        }

        // Track last access to each resource (pass index, access type, queue)
        const last_access = try self.allocator.alloc(?AccessState, self.resources.items.len);
        defer self.allocator.free(last_access);
        @memset(last_access, null);

        // Count how many passes each pass depends on (for topological sorting)
        var dependency_counts = std.ArrayList(usize).empty;
        defer dependency_counts.deinit(self.allocator);

        // Main loop: process each pass and collect its dependencies
        for (self.passes.items) |pass| {
            if (!pass.enabled) {
                continue;
            }
            const pass_index: u16 = @intCast(enabled_passes.items.len);
            try dependency_counts.append(self.allocator, 0);

            // Process input resources (reads)
            for (pass.inputs) |input| {
                try registerResourceUse(self.allocator, &dependencies, &dependency_counts, resource_lifetimes, last_access, pass_index, pass.queue, input);
            }
            // Process output resources (writes)
            for (pass.outputs) |output| {
                try registerResourceUse(self.allocator, &dependencies, &dependency_counts, resource_lifetimes, last_access, pass_index, pass.queue, output);
            }

            // Append compiled pass with final dependency count
            try enabled_passes.append(self.allocator, .{
                .pass_index = pass_index,
                .name = pass.name,
                .kind = pass.kind,
                .queue = pass.queue,
                .inputs = pass.inputs,
                .outputs = pass.outputs,
                .dependency_count = dependency_counts.items[pass_index],
            });
        }

        self.compiled = .{
            .allocator = self.allocator,
            .execution = try enabled_passes.toOwnedSlice(self.allocator),
            .dependencies = try dependencies.toOwnedSlice(self.allocator),
            .resource_lifetimes = resource_lifetimes,
        };
    }

    pub fn passCount(self: *const RenderGraph) usize {
        if (self.compiled) |compiled| {
            return compiled.execution.len;
        }
        return self.passes.items.len;
    }

    pub fn resourceCount(self: *const RenderGraph) usize {
        return self.resources.items.len;
    }

    pub fn compiledPasses(self: *const RenderGraph) []const CompiledPass {
        return if (self.compiled) |compiled| compiled.execution else &.{};
    }

    pub fn lifetimes(self: *const RenderGraph) []const ResourceLifetime {
        return if (self.compiled) |compiled| compiled.resource_lifetimes else &.{};
    }

    /// Build explicit transition intents from dependency edges.
    ///
    /// Phase 3 backends can map each BarrierPlan to platform-specific barriers:
    /// - Metal: memoryBarrier / fence scopes
    /// - Vulkan: vkCmdPipelineBarrier2
    /// - DX12: ResourceBarrier
    pub fn buildBarrierPlanAlloc(self: *const RenderGraph, allocator: std.mem.Allocator) ![]BarrierPlan {
        const compiled = self.compiled orelse return allocator.alloc(BarrierPlan, 0);

        var plans = std.ArrayList(BarrierPlan).empty;
        defer plans.deinit(allocator);

        for (compiled.dependencies) |edge| {
            const resource_node = self.resources.items[edge.resource];
            try plans.append(allocator, .{
                .from_pass = edge.from_pass,
                .to_pass = edge.to_pass,
                .resource = edge.resource,
                .src_state = accessToBarrierState(edge.previous_access, resource_node.kind),
                .dst_state = accessToBarrierState(edge.next_access, resource_node.kind),
                .cross_queue = edge.cross_queue,
            });
        }

        return plans.toOwnedSlice(allocator);
    }

    pub fn allocatePassStats(self: *const RenderGraph, allocator: std.mem.Allocator) ![]PassExecutionStat {
        const compiled = self.compiled orelse return allocator.alloc(PassExecutionStat, 0);
        const stats = try allocator.alloc(PassExecutionStat, compiled.execution.len);
        for (compiled.execution, 0..) |pass, index| {
            stats[index] = .{
                .name = pass.name,
                .kind = pass.kind,
                .queue = pass.queue,
                .input_count = pass.inputs.len,
                .output_count = pass.outputs.len,
                .dependency_count = pass.dependency_count,
            };
        }
        return stats;
    }

    pub fn recordPassStat(
        self: *const RenderGraph,
        stats: []PassExecutionStat,
        kind: PassKind,
        cpu_time_ns: u64,
        draw_calls: usize,
        triangles_drawn: usize,
    ) void {
        _ = self;
        for (stats) |*stat| {
            if (stat.kind == kind) {
                stat.cpu_time_ns += cpu_time_ns;
                stat.draw_calls += draw_calls;
                stat.triangles_drawn += triangles_drawn;
                return;
            }
        }
    }

    pub fn exportDotAlloc(self: *const RenderGraph, allocator: std.mem.Allocator) ![]u8 {
        const compiled = self.compiled orelse return allocator.dupe(u8, "digraph RenderGraph {}\n");
        var output = std.ArrayList(u8).empty;
        defer output.deinit(allocator);

        try output.writer(allocator).print("digraph RenderGraph {{\n  rankdir=LR;\n", .{});
        for (self.resources.items, 0..) |resource, index| {
            try output.writer(allocator).print(
                "  resource_{d} [shape=ellipse,label=\"{s}\"];\n",
                .{ index, resource.name },
            );
        }
        for (compiled.execution, 0..) |pass, index| {
            try output.writer(allocator).print(
                "  pass_{d} [shape=box,label=\"{s}\"];\n",
                .{ index, pass.name },
            );
            for (pass.inputs) |input| {
                try output.writer(allocator).print("  resource_{d} -> pass_{d};\n", .{ input.resource, index });
            }
            for (pass.outputs) |resource_use| {
                try output.writer(allocator).print("  pass_{d} -> resource_{d};\n", .{ index, resource_use.resource });
            }
        }
        try output.writer(allocator).print("}}\n", .{});
        return output.toOwnedSlice(allocator);
    }

    pub fn exportJsonAlloc(self: *const RenderGraph, allocator: std.mem.Allocator) ![]u8 {
        const compiled = self.compiled orelse return allocator.dupe(u8, "{}\n");
        return stringifyAlloc(allocator, GraphJson{
            .resources = self.resources.items,
            .passes = compiled.execution,
            .dependencies = compiled.dependencies,
            .lifetimes = compiled.resource_lifetimes,
        });
    }

    pub fn writeExports(self: *const RenderGraph, dot_path: []const u8, json_path: []const u8) !void {
        const dot = try self.exportDotAlloc(self.allocator);
        defer self.allocator.free(dot);
        const json = try self.exportJsonAlloc(self.allocator);
        defer self.allocator.free(json);
        try writeTextFile(dot_path, dot);
        try writeTextFile(json_path, json);
    }

    pub fn writeFrameReport(
        self: *const RenderGraph,
        allocator: std.mem.Allocator,
        path: []const u8,
        backend_name: []const u8,
        draw_calls: usize,
        triangles_drawn: usize,
        stats: []const PassExecutionStat,
    ) !void {
        const report = GraphReport{
            .backend = backend_name,
            .draw_calls = draw_calls,
            .triangles_drawn = triangles_drawn,
            .resource_count = self.resourceCount(),
            .pass_count = self.passCount(),
            .passes = stats,
            .lifetimes = self.lifetimes(),
        };
        const encoded = try stringifyAlloc(allocator, report);
        defer allocator.free(encoded);
        try writeTextFile(path, encoded);
    }
};

fn registerResourceUse(
    allocator: std.mem.Allocator,
    dependencies: *std.ArrayList(DependencyEdge),
    dependency_counts: *std.ArrayList(usize),
    lifetimes: []ResourceLifetime,
    last_access: []?AccessState,
    pass_index: u16,
    queue: QueueClass,
    use_ref: PassResourceUse,
) !void {
    if (use_ref.resource >= lifetimes.len) {
        return error.ResourceIndexOutOfBounds;
    }

    var lifetime = &lifetimes[use_ref.resource];
    if (lifetime.first_use_pass == null) {
        lifetime.first_use_pass = pass_index;
    }
    lifetime.last_use_pass = pass_index;

    if (last_access[use_ref.resource]) |previous| {
        try appendDependencyIfMissing(allocator, dependencies, .{
            .from_pass = previous.pass,
            .to_pass = pass_index,
            .resource = use_ref.resource,
            .previous_access = previous.access,
            .next_access = use_ref.access,
            .cross_queue = previous.queue != queue,
        });
        dependency_counts.items[pass_index] = dependencyCountsForPass(dependencies.items, pass_index);
    }

    last_access[use_ref.resource] = .{
        .pass = pass_index,
        .access = use_ref.access,
        .queue = queue,
    };
}

fn appendDependencyIfMissing(allocator: std.mem.Allocator, list: *std.ArrayList(DependencyEdge), edge: DependencyEdge) !void {
    for (list.items) |existing| {
        if (existing.from_pass == edge.from_pass and existing.to_pass == edge.to_pass and existing.resource == edge.resource) {
            return;
        }
    }
    try list.append(allocator, edge);
}

fn dependencyCountsForPass(edges: []const DependencyEdge, pass_index: u16) usize {
    var count: usize = 0;
    for (edges) |edge| {
        if (edge.to_pass == pass_index) {
            count += 1;
        }
    }
    return count;
}

fn accessToBarrierState(access: ResourceAccess, kind: ResourceKind) BarrierState {
    if (kind == .swapchain and access == .write) return .present;
    return switch (access) {
        .read => .shader_read,
        .write => .shader_write,
        .read_write => .shader_read_write,
    };
}

fn stringifyAlloc(allocator: std.mem.Allocator, value: anytype) ![]u8 {
    var output = std.ArrayList(u8).empty;
    defer output.deinit(allocator);

    var writer = output.writer(allocator);
    var adapter_buffer: [4096]u8 = undefined;
    var writer_adapter = writer.adaptToNewApi(&adapter_buffer);
    try std.json.Stringify.value(value, .{ .whitespace = .indent_2 }, &writer_adapter.new_interface);
    try writer_adapter.new_interface.flush();
    if (writer_adapter.err) |err| {
        return err;
    }
    return output.toOwnedSlice(allocator);
}

fn writeTextFile(path: []const u8, contents: []const u8) !void {
    if (std.fs.path.dirname(path)) |directory| {
        try std.fs.cwd().makePath(directory);
    }
    try std.fs.cwd().writeFile(.{
        .sub_path = path,
        .data = contents,
    });
}

test "default render graph compiles with resource lifetimes" {
    var graph = try RenderGraph.initDefault3D(std.testing.allocator);
    defer graph.deinit();

    try std.testing.expectEqual(@as(usize, 7), graph.resourceCount());
    try std.testing.expectEqual(@as(usize, 10), graph.passCount());
    const lifetimes = graph.lifetimes();
    try std.testing.expect(lifetimes.len == 7);
    try std.testing.expect(lifetimes[1].first_use_pass != null);
    try std.testing.expect(lifetimes[5].last_use_pass != null);
}

test "render graph exports deterministic dot" {
    var graph = try RenderGraph.initDefault3D(std.testing.allocator);
    defer graph.deinit();

    const dot = try graph.exportDotAlloc(std.testing.allocator);
    defer std.testing.allocator.free(dot);

    try std.testing.expect(std.mem.indexOf(u8, dot, "OutlinePass") != null);
    try std.testing.expect(std.mem.indexOf(u8, dot, "SceneDepth") != null);
    try std.testing.expect(std.mem.indexOf(u8, dot, "resource_1 -> pass_2") != null);
}

test "render graph builds barrier plans" {
    var graph = try RenderGraph.initDefault3D(std.testing.allocator);
    defer graph.deinit();

    const plans = try graph.buildBarrierPlanAlloc(std.testing.allocator);
    defer std.testing.allocator.free(plans);

    try std.testing.expect(plans.len > 0);
    try std.testing.expect(plans[0].to_pass >= plans[0].from_pass);
}
